# -*- coding: utf-8 -*-
"""AgriAdvice - Original.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yCPL9pLu2Us8Vbio-b7lutVG5RG3gDr
"""

# 1. Install LangGraph for stateful agent orchestration
!pip install -q langgraph

# 2. Install the lightweight Guardrail dependencies
!pip install -q transformers optimum # Optimum helps run smaller models faster

# 1. Install LangGraph for the automated state machine
!pip install -q langgraph

# 2. Install AI4Bharat's Indic TTS dependencies (Parler-TTS backend)
!pip install -q git+https://github.com/huggingface/parler-tts.git

# 3. Upgrade Transformers for Qwen2.5 / Llama 3.1 support
!pip install -q --upgrade transformers accelerate bitsandbytes

# Forcing the environment to use the exact version required by the voice model
!pip install -q transformers==4.46.1 protobuf>=5.29.1

from typing import TypedDict, Optional

# We are defining the exact blueprint of our Manager's Clipboard (The State)
class AgenticState(TypedDict):
    user_audio_path: str          # Where the original voice recording is saved
    detected_language: str        # e.g., "hi" for Hindi, "ta" for Tamil, "en" for English
    user_transcript: str          # The text of what the user actually said
    retrieved_context: str        # The data pulled from your background dataset
    draft_response: str           # The AI's initial answer (before safety checks)
    final_safe_response: str      # The approved, policy-checked text
    output_audio_path: str        # Where the final AI voice file is saved
    error_flag: Optional[str]     # A red flag if something goes wrong (like pure static)

print("✅ Blueprint for the Agentic State has been successfully created in memory!")

from faster_whisper import WhisperModel

# 1. We specify the model size
model_size = "large-v3-turbo"

# 2. We explicitly attach it to the GPU ("cuda") and cut its memory size in half ("float16")
audio_model = WhisperModel(model_size, device="cuda", compute_type="float16")

print("✅ The Ear is fully awake, loaded into VRAM, and listening!")

# Downloading the faste whisper module
!pip install -q faster-whisper

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline

# 1. Hardware Optimization: Configure 4-bit quantization to shrink the 7B model from 14GB to ~5GB
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

# 2. Define the Polyglot LLM
model_id = "Qwen/Qwen2.5-7B-Instruct"

# 3. Load the Tokenizer (Text -> Numbers) and the Model (The Neural Network)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=quantization_config,
    device_map="auto"  # Automatically maps the model weights to the GPU
)

# 4. Create the Generation Pipeline to handle the actual reasoning process
reasoning_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=256,  # Hard cap for prototype speed
    temperature=0.3,     # Low temperature forces logical, factual responses over creative ones
)

# 5. Define the actual Node Function that our LangGraph Manager will call
def brain_node(state):
    # Extract the necessary variables from the moving state dictionary
    user_text = state["user_transcript"]
    lang = state["detected_language"]

    # We use a placeholder for context right now until we build the RAG (Retrieval) Node
    context = state.get("retrieved_context", "No background context provided yet.")

    # Dynamically inject the detected language into the system prompt to force the output language
    system_prompt = f"""You are an intelligent reasoning agent.
    The user spoke in language code: '{lang}'.
    Context: {context}

    Answer the user's query using the context.
    CRITICAL: Your final output MUST be written in the exact same language as the user's language code ({lang})."""

    # Format the messages in the standard chat template
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_text}
    ]

    # Generate the reasoning and extract the raw text
    outputs = reasoning_pipeline(messages)
    generated_text = outputs[0]["generated_text"][-1]["content"]

    # Update the state clipboard with the drafted response
    state["draft_response"] = generated_text

    return state

from langchain_community.embeddings import HuggingFaceBgeEmbeddings
from langchain_community.vectorstores import FAISS

# 1. Initialize the Embedding Engine (The Cartographer)
# BAAI/bge-small-en-v1.5 maps text to 384-dimensional vectors.
# It is chosen for its extreme efficiency, leaving VRAM available for the LLM.
embedding_model_name = "BAAI/bge-small-en-v1.5"
embedding_kwargs = {"device": "cuda"} # Hardware acceleration constraint
encode_kwargs = {"normalize_embeddings": True} # Normalizes vectors to length 1 for faster cosine similarity

embeddings = HuggingFaceBgeEmbeddings(
    model_name=embedding_model_name,
    model_kwargs=embedding_kwargs,
    encode_kwargs=encode_kwargs
)

# 2. Establish the Prototypic Substrate (The Dataset)
# For the bare-minimum prototype, we hardcode a small array of contextual data.
# In a production state, this array is populated by a DocumentLoader parsing PDFs/CSVs.
prototypic_dataset = [
    "The multi-modal AI system utilizes Faster-Whisper to transcribe audio inputs into discrete text tokens.",
    "The reasoning architecture relies on a 4-bit quantized Qwen 7B model to operate within the 16GB VRAM constraint of a T4 GPU.",
    "The LangGraph orchestrator acts as a stateful machine, routing data through a defined dictionary blueprint called the AgenticState.",
    "AI4Bharat provides the crucial polyglot dependencies required to synthesize Indian languages accurately."
]

# 3. Construct the Vector Index (The Spatial Database)
# FAISS mathematically indexes the strings against the embedding coordinates in VRAM.
vector_database = FAISS.from_texts(prototypic_dataset, embeddings)

# 4. Instantiate the Retrieval Mechanism
# 'k=2' dictates that the algorithm will only extract the top 2 closest semantic matches to prevent context window overflow.
retriever = vector_database.as_retriever(search_kwargs={"k": 2})

# 5. Define the Node Function (The API for LangGraph)
def researcher_node(state):
    # Extract the transcribed query from the state dictionary
    query = state["user_transcript"]

    # Execute the geometric similarity search against the FAISS index
    retrieved_documents = retriever.invoke(query)

    # Concatenate the retrieved data objects into a continuous string format for LLM ingestion
    context_string = "\n".join([doc.page_content for doc in retrieved_documents])

    # Mutate the state dictionary to include the new context
    state["retrieved_context"] = context_string

    return state

# Downloading the RAG Ecosystem (The Cartographer and the Spatial Database)
# We use -q to keep the installation quiet and clean
!pip install -q langchain langchain-community sentence-transformers faiss-gpu

# Swapping the GPU spatial database for the universally compatible CPU version
!pip install -q langchain langchain-community sentence-transformers faiss-cpu

# Forcing the environment to downgrade 'requests' to exactly what Colab requires
!pip install -q requests==2.32.4

# Prioritizing the AI ecosystem's requirements
!pip install -q requests>=2.32.5

from langchain_community.embeddings import HuggingFaceBgeEmbeddings
from langchain_community.vectorstores import FAISS

# 1. Initialize the Embedding Engine (The Cartographer)
# BAAI/bge-small-en-v1.5 maps text to 384-dimensional vectors.
# It is chosen for its extreme efficiency, leaving VRAM available for the LLM.
embedding_model_name = "BAAI/bge-small-en-v1.5"
embedding_kwargs = {"device": "cuda"} # Hardware acceleration constraint
encode_kwargs = {"normalize_embeddings": True} # Normalizes vectors to length 1 for faster cosine similarity

embeddings = HuggingFaceBgeEmbeddings(
    model_name=embedding_model_name,
    model_kwargs=embedding_kwargs,
    encode_kwargs=encode_kwargs
)

# 2. Establish the Prototypic Substrate (The Dataset)
# For the bare-minimum prototype, we hardcode a small array of contextual data.
# In a production state, this array is populated by a DocumentLoader parsing PDFs/CSVs.
prototypic_dataset = [
    "The multi-modal AI system utilizes Faster-Whisper to transcribe audio inputs into discrete text tokens.",
    "The reasoning architecture relies on a 4-bit quantized Qwen 7B model to operate within the 16GB VRAM constraint of a T4 GPU.",
    "The LangGraph orchestrator acts as a stateful machine, routing data through a defined dictionary blueprint called the AgenticState.",
    "AI4Bharat provides the crucial polyglot dependencies required to synthesize Indian languages accurately."
]

# 3. Construct the Vector Index (The Spatial Database)
# FAISS mathematically indexes the strings against the embedding coordinates in VRAM.
vector_database = FAISS.from_texts(prototypic_dataset, embeddings)

# 4. Instantiate the Retrieval Mechanism
# 'k=2' dictates that the algorithm will only extract the top 2 closest semantic matches to prevent context window overflow.
retriever = vector_database.as_retriever(search_kwargs={"k": 2})

# 5. Define the Node Function (The API for LangGraph)
def researcher_node(state):
    # Extract the transcribed query from the state dictionary
    query = state["user_transcript"]

    # Execute the geometric similarity search against the FAISS index
    retrieved_documents = retriever.invoke(query)

    # Concatenate the retrieved data objects into a continuous string format for LLM ingestion
    context_string = "\n".join([doc.page_content for doc in retrieved_documents])

    # Mutate the state dictionary to include the new context
    state["retrieved_context"] = context_string

    return state

from langgraph.graph import StateGraph, START, END

# 1. Standardize the Ear Interface
# Wraps the acoustic model into a node that strictly interacts with the AgenticState dictionary
def ear_node(state):
    # Retrieve the raw acoustic data path
    audio_path = state["user_audio_path"]

    # Execute the acoustic-to-discrete-token transformation
    segments, info = audio_model.transcribe(audio_path, beam_size=5)

    # Concatenate the token generator object into a continuous string
    full_transcript = " ".join([segment.text for segment in segments])

    # Mutate the state clipboard with the extracted data
    state["detected_language"] = info.language
    state["user_transcript"] = full_transcript

    return state

# 2. Initialize the Orchestrator
# Instantiate the graph with the exact type-hinted dictionary blueprint
workflow = StateGraph(AgenticState)

# 3. Mount the Compute Nodes
# Attach our isolated functions to the graph memory space
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)

# 4. Define the Directed Edges (Routing Logic)
# Establish the sequential, automated flow: Audio -> Semantic Search -> LLM Generation
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", END)

# 5. Compile the Architecture
# Locks the graph topology and optimizes the execution paths in memory
ai_pipeline = workflow.compile()

# 1. Define the Initial State (The Input Vector)
# CRITICAL: Ensure the filename exactly matches the file you uploaded to Colab's sidebar.
initial_state = {
    "user_audio_path": "sample_audio_1.mp3.mpeg",
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("Initiating Pipeline... Listening and Reasoning (This takes 30-60 seconds)")

# 2. Execute the Graph Traversal
# Triggers the automated cascade: Ear -> Researcher -> Brain.
final_state = ai_pipeline.invoke(initial_state)

# 3. Output Extraction
print("\n--- Final Extracted State ---")
print(f"Detected Language: {final_state['detected_language']}")
print(f"Your Transcript:   {final_state['user_transcript']}")
print(f"Retrieved Context: {final_state['retrieved_context']}")
print(f"\nAI Reasoned Output:\n{final_state['draft_response']}")



# 1. Define the Initial State (The Input Vector)
# CRITICAL: Ensure the filename exactly matches the file you uploaded to Colab's sidebar.
initial_state = {
    "user_audio_path": "sample_audio_1.mp3.mpeg",
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("Initiating Pipeline... Listening and Reasoning (This takes 30-60 seconds)")

# 2. Execute the Graph Traversal
# Triggers the automated cascade: Ear -> Researcher -> Brain.
final_state = ai_pipeline.invoke(initial_state)

# 3. Output Extraction
print("\n--- Final Extracted State ---")
print(f"Detected Language: {final_state['detected_language']}")
print(f"Your Transcript:   {final_state['user_transcript']}")
print(f"Retrieved Context: {final_state['retrieved_context']}")
print(f"\nAI Reasoned Output:\n{final_state['draft_response']}")

from langgraph.graph import StateGraph, START, END

# 1. The Patched Ear Interface
def ear_node(state):
    audio_path = state["user_audio_path"]
    segments, info = audio_model.transcribe(audio_path, beam_size=5)
    full_transcript = " ".join([segment.text for segment in segments])

    # --- EDGE CASE OVERRIDE LOGIC ---
    detected_lang = info.language
    # If the acoustic model confuses Hindustani audio for Urdu, force it to Hindi
    if detected_lang == "ur":
        detected_lang = "hi"
    # --------------------------------

    state["detected_language"] = detected_lang
    state["user_transcript"] = full_transcript

    return state

# 2. Re-Initialize the Orchestrator
workflow = StateGraph(AgenticState)

# 3. Mount the Compute Nodes
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)

# 4. Define the Directed Edges
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", END)

# 5. Re-Compile the Architecture
ai_pipeline = workflow.compile()

# 1. Define the Initial State (The Input Vector)
# CRITICAL: Ensure the filename exactly matches the file you uploaded to Colab's sidebar.
initial_state = {
    "user_audio_path": "sample_audio_1.mpeg",
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("Initiating Pipeline... Listening and Reasoning (This takes 30-60 seconds)")

# 2. Execute the Graph Traversal
# Triggers the automated cascade: Ear -> Researcher -> Brain.
final_state = ai_pipeline.invoke(initial_state)

# 3. Output Extraction
print("\n--- Final Extracted State ---")
print(f"Detected Language: {final_state['detected_language']}")
print(f"Your Transcript:   {final_state['user_transcript']}")
print(f"Retrieved Context: {final_state['retrieved_context']}")
print(f"\nAI Reasoned Output:\n{final_state['draft_response']}")

from transformers import pipeline
from langgraph.graph import StateGraph, START, END

# ==========================================
# 1. Initialize the Policy Engine
# ==========================================
# We load a highly optimized, sub-1GB model strictly for classification.
# This runs alongside your 7B LLM without exceeding the 16GB VRAM limit.
policy_classifier = pipeline(
    "zero-shot-classification",
    model="MoritzLaurer/DeBERTa-v3-base-zeroshot-v2.0",
    device="cuda"
)

# ==========================================
# 2. Define the Guardrail Node
# ==========================================
def guardrail_node(state):
    # Retrieve the raw text drafted by the Brain
    drafted_text = state["draft_response"]

    # Define the strict boundaries of our system
    policy_labels = ["safe and helpful", "toxic, hateful, or harmful advice"]

    # Execute the probability matrix scan
    classification = policy_classifier(drafted_text, policy_labels)

    # Extract the label with the highest mathematical confidence
    top_label = classification['labels'][0]

    # The Routing Logic:
    if top_label == "toxic, hateful, or harmful advice":
        # Overwrite the drafted response with a hardcoded safety fallback
        state["final_safe_response"] = "Policy Override: I cannot fulfill this request safely."
        state["error_flag"] = "Safety Violation Triggered"
    else:
        # If safe, promote the draft to the final output pipeline
        state["final_safe_response"] = drafted_text

    return state

# ==========================================
# 3. Re-Architecting the Assembly Line (V3)
# ==========================================
workflow = StateGraph(AgenticState)

# Mount all 4 compute nodes
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)
workflow.add_node("guardrail", guardrail_node) # <- NEW NODE MOUNTED

# Define the new Directed Edges (Routing)
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", "guardrail")        # Brain now hands off to Guardrail
workflow.add_edge("guardrail", END)            # Guardrail is currently the end of the line

# Compile the updated graph
ai_pipeline = workflow.compile()

import torch
import soundfile as sf
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer
from langgraph.graph import StateGraph, START, END

# ==========================================
# 1. Initialize the Acoustic Synthesizer
# ==========================================
# We load a lightweight TTS model into the remaining GPU memory.
# (Using the highly stable mini-v1 which supports conditional voice prompting)
tts_model_name = "parler-tts/parler-tts-mini-v1"
tts_tokenizer = AutoTokenizer.from_pretrained(tts_model_name)
tts_model = ParlerTTSForConditionalGeneration.from_pretrained(tts_model_name).to("cuda")

# ==========================================
# 2. Define the Voicebox Node
# ==========================================
def voicebox_node(state):
    # Extract the finalized, policy-cleared text
    text_to_speak = state["final_safe_response"]

    # We define the acoustic style (this can be dynamically altered later)
    voice_description = "A clear, professional female voice speaking at a moderate pace with a neutral tone."

    # Tokenize both the style prompt and the actual text
    input_ids = tts_tokenizer(voice_description, return_tensors="pt").input_ids.to("cuda")
    prompt_input_ids = tts_tokenizer(text_to_speak, return_tensors="pt").input_ids.to("cuda")

    # Generate the raw audio waveform
    generation = tts_model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
    audio_waveform = generation.cpu().numpy().squeeze()

    # Save the waveform to the Colab hard drive as a .wav file
    output_filename = "ai_final_response.wav"
    sf.write(output_filename, audio_waveform, tts_model.config.sampling_rate)

    # Mutate the state with the final physical file path
    state["output_audio_path"] = output_filename

    return state

# ==========================================
# 3. The Final Architecture Assembly (V4)
# ==========================================
workflow = StateGraph(AgenticState)

# Mount all 5 compute nodes
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)
workflow.add_node("guardrail", guardrail_node)
workflow.add_node("voicebox", voicebox_node) # <- THE FINAL NODE

# Define the complete closed-loop routing
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", "guardrail")
workflow.add_edge("guardrail", "voicebox")   # Cleared text goes to the Voicebox
workflow.add_edge("voicebox", END)           # The audio file is the final physical output

# Compile the Master Graph
ai_pipeline = workflow.compile()

from IPython.display import Audio, display

# 1. The Blank Input Vector
initial_state = {
    "user_audio_path": "sample_audio_1.mpeg", # Your uploaded voice clip
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("🚀 INITIATING FULL MASTER PIPELINE...")
print("Nodes executing: Ear -> Researcher -> Brain -> Guardrail -> Voicebox")

# 2. Trigger the Automated Assembly Line
final_state = ai_pipeline.invoke(initial_state)

# 3. Display the final systemic outputs
print("\n" + "="*50)
print(f"✅ Language Detected: {final_state['detected_language']}")
print(f"✅ User Transcript:   {final_state['user_transcript']}")
print(f"✅ Guardrail Cleared: {final_state['final_safe_response']}")
print("="*50)

# 4. Generate the Audio Interface
print("\n🔊 AI Audio Output:")
display(Audio(final_state['output_audio_path'], autoplay=True))