# -*- coding: utf-8 -*-
"""AgriAdvice - Original.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yCPL9pLu2Us8Vbio-b7lutVG5RG3gDr
"""

import os
from google.colab import drive

# ==========================================
# Phase 1: Storage & Cache Architecture
# ==========================================
print("🔗 Mounting Google Drive for Persistent Storage...")
drive.mount('/content/drive')
CACHE_DIR = '/content/drive/MyDrive/AgriTech_Swarm_Cache'
os.makedirs(CACHE_DIR, exist_ok=True)
os.environ['HF_HOME'] = CACHE_DIR
os.environ['TORCH_HOME'] = CACHE_DIR

# ==========================================
# Phase 2: The Multi-Agent Tech Stack
# ==========================================
print("⚙️ Installing Swarm Dependencies...")
!pip install -q click>=8.2.1 langgraph transformers==4.46.1 accelerate bitsandbytes faster-whisper gtts deep-translator aiohttp sentence-transformers requests>=2.32.5

# ==========================================
# Phase 3: Waking the Core Engines
# ==========================================
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline
from faster_whisper import WhisperModel

print("🧠 Loading Core Engines into VRAM...")

# 1. The Perception Engine (Whisper)
audio_model = WhisperModel("large-v3-turbo", device="cuda", compute_type="float16", download_root=CACHE_DIR)

# 2. The Cognitive Engine (Qwen 7B) - Now explicitly for English Deep Reasoning
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)
llm_tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct")
llm_model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-7B-Instruct",
    quantization_config=quantization_config,
    device_map="auto"
)
reasoning_pipeline = pipeline("text-generation", model=llm_model, tokenizer=llm_tokenizer, device_map="auto")

# 3. The Gatekeeper & Policy Engine (DeBERTa)
policy_classifier = pipeline("zero-shot-classification", model="MoritzLaurer/DeBERTa-v3-base-zeroshot-v2.0", device="cuda")

print("✅ Swarm Infrastructure Online. Ready to build Agent Squads.")

from typing import TypedDict, Dict, Any, Optional
from langgraph.graph import StateGraph, START, END

# ==========================================
# The Central Nervous System (Swarm State)
# ==========================================
class SwarmState(TypedDict):
    # Squad 1: Perception & Translation
    user_audio_path: str
    detected_language: str
    native_transcript: str
    english_query: str          # The entire system will run on this clean English string

    # Squad 2: Data Harvesters
    extracted_entities: dict    # e.g., {"location": "Kota", "crop": "Cotton"}
    harvested_data: Dict[str, Any] # Holds the async API JSONs

    # Squad 3: Cognitive & Compliance
    agronomist_draft_en: str    # The expert advice in English
    compliance_flag: str        # Pass/Fail status

    # Squad 4: Output Synthesis
    final_translated_text: str  # Back to native language
    output_audio_path: str
    routing_error: Optional[str] # Triggers the short-circuit if profanity/out-of-domain

from deep_translator import GoogleTranslator

# ==========================================
# Squad 1, Agent 1: The Perception Agent
# ==========================================
def perception_node(state: SwarmState):
    audio_path = state["user_audio_path"]

    # 1. Acoustic Ingestion & Transcription
    segments, info = audio_model.transcribe(audio_path, beam_size=5)
    native_text = " ".join([segment.text for segment in segments])

    # 2. The Hindustani Acoustic Patch
    detected_lang = info.language
    if detected_lang == "ur":
        detected_lang = "hi"

    # 3. Language Decoupling (Translate to English)
    if detected_lang != "en":
        english_text = GoogleTranslator(source=detected_lang, target='en').translate(native_text)
    else:
        english_text = native_text

    # Update the Swarm Clipboard
    state["detected_language"] = detected_lang
    state["native_transcript"] = native_text
    state["english_query"] = english_text

    return state

# ==========================================
# Squad 1, Agent 2: The Semantic Gatekeeper
# ==========================================
def gatekeeper_node(state: SwarmState):
    # The Gatekeeper only evaluates the clean English query
    query = state["english_query"]

    # Strict boundary definitions
    policy_labels = [
        "agricultural question about farming, crops, weather, or soil",
        "profanity, toxic, or offensive language",
        "general chat, technology, movies, or out of domain topics"
    ]

    # Microscopic probability scan (Takes ~50 milliseconds)
    classification = policy_classifier(query, policy_labels)
    top_label = classification['labels'][0]

    lang = state["detected_language"]

    # ---------------------------------------------------------
    # The Short-Circuit Routing Logic
    # ---------------------------------------------------------
    if top_label == "profanity, toxic, or offensive language":
        state["routing_error"] = "PROFANITY_DETECTED"
        rejection_en = "Please use respectful language. I am an agricultural assistant."
        # Translate rejection back to native dialect
        state["final_translated_text"] = GoogleTranslator(source='en', target=lang).translate(rejection_en)

    elif top_label == "general chat, technology, movies, or out of domain topics":
        state["routing_error"] = "OUT_OF_DOMAIN"
        rejection_en = "I am an agricultural expert. Please ask questions related to farming, crops, or soil."
        # Translate rejection back to native dialect
        state["final_translated_text"] = GoogleTranslator(source='en', target=lang).translate(rejection_en)

    else:
        # Query is safe. Green light for the rest of the Swarm.
        state["routing_error"] = None

    return state

import asyncio
import aiohttp

# ==========================================
# Squad 2: The Asynchronous Data Harvesters
# ==========================================

# Harvester 1: The Meteo-Agent (Fully Functional Open-Source)
async def fetch_weather(session, location_name):
    try:
        # Step 1: Geocoding (Text to Coordinates)
        geo_url = f"https://geocoding-api.open-meteo.com/v1/search?name={location_name}&count=1"
        async with session.get(geo_url, timeout=5) as geo_res:
            geo_data = await geo_res.json()

            if not geo_data.get("results"):
                return {"weather": f"Could not find coordinates for {location_name}."}

            lat = geo_data["results"][0]["latitude"]
            lon = geo_data["results"][0]["longitude"]

        # Step 2: Hyper-local Weather Fetch
        weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true"
        async with session.get(weather_url, timeout=5) as weather_res:
            w_data = await weather_res.json()
            temp = w_data["current_weather"]["temperature"]
            wind = w_data["current_weather"]["windspeed"]
            return {"weather": f"Temp: {temp}°C, Wind: {wind} km/h at {lat},{lon}"}

    except Exception as e:
        return {"weather": f"Meteo-Agent Offline: {str(e)}"}

# Harvester 2: The Mandi-Agent (Structured Prototype)
async def fetch_market(session, crop_name):
    # In production, this hits: https://api.data.gov.in/resource/...
    await asyncio.sleep(0.5) # Simulating network latency for the OGD API

    if crop_name.lower() not in ["general", "", "unknown"]:
        return {"market": f"{crop_name.capitalize()} trading at approx 2,450 INR/Quintal (Uptrend 2.1%)."}
    return {"market": "No specific crop identified for market analysis."}

# Harvester 3: The Soil-Agent (Structured Prototype)
async def fetch_soil(session, location_name):
    # In production, this queries the Soil Health Card (SHC) database by region
    await asyncio.sleep(0.6) # Simulating database query latency
    return {"soil": f"Regional profile for {location_name}: Black Cotton Soil. Nitrogen: Deficient. Phosphorus: Medium. pH: 7.4."}

# ==========================================
# The Data Orchestrator Node
# ==========================================
# Notice the 'async def'. LangGraph natively supports async nodes.
async def data_orchestrator_node(state: SwarmState):
    # Retrieve the extracted entities from Squad 1 (or default if missing)
    entities = state.get("extracted_params", {})
    location = entities.get("location", "Hubballi")
    crop = entities.get("crop", "General")

    # Initialize the high-performance async HTTP session
    async with aiohttp.ClientSession() as session:
        # Dispatch all three Harvester Agents concurrently
        results = await asyncio.gather(
            fetch_weather(session, location),
            fetch_market(session, crop),
            fetch_soil(session, location)
        )

    # Fuse the parallel JSON responses into a single interconnected dictionary
    fused_data = {}
    for res in results:
        fused_data.update(res)

    # Inject the fused data back into the Swarm's Central Nervous System
    state["harvested_data"] = fused_data

    return state

# ==========================================
# Squad 3, Agent 1: The Master Agronomist
# ==========================================
def agronomist_node(state: SwarmState):
    query = state["english_query"]
    data = state.get("harvested_data", {})
    crop = state.get("extracted_entities", {}).get("crop", "Unknown")

    # Advanced Cognitive Prompting: Handling Edge Cases & Deep Routing
    system_prompt = f"""You are an elite Agricultural AI. You analyze variables strictly from first principles.
    Target Crop: {crop.upper()}

    REAL-TIME SENSORY DATA:
    {data}

    CRITICAL REASONING PROTOCOL:
    1. If sensory data contains 'Offline' or errors, explicitly state you are relying on seasonal heuristic knowledge.
    2. Connect the variables: Explain exactly how the soil pH/type interacts with the current weather to affect the crop.
    3. Feasibility: Recommend solutions that are economically viable for a rural farmer.

    Format your response in highly structured English:
    [SITUATION METRICS]: Brief fusion of the data.
    [SYSTEMIC ANALYSIS]: How the variables currently interact.
    [ACTIONABLE DIRECTIVES]: 3 precise, granular steps for the next 48 hours.
    """

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": query}]

    # Execute deep processing. Because it's English, 1024 tokens is highly abundant.
    outputs = reasoning_pipeline(
        messages,
        max_new_tokens=1024,
        temperature=0.3, # Low temperature for high precision/low hallucination
        pad_token_id=llm_tokenizer.eos_token_id
    )

    state["agronomist_draft_en"] = outputs[0]["generated_text"][-1]["content"]
    return state

# ==========================================
# Squad 3, Agent 2: The Policy Auditor
# ==========================================
def compliance_node(state: SwarmState):
    draft = state["agronomist_draft_en"]

    # We scan the English draft for severe violations
    labels = ["safe farming advice", "recommends banned chemicals, stubble burning, or hazardous practices"]
    classification = policy_classifier(draft, labels)

    if classification['labels'][0] == "recommends banned chemicals, stubble burning, or hazardous practices":
        state["compliance_flag"] = "FAIL"
        # Override the draft with a hardcoded safety message
        state["agronomist_draft_en"] = "Safety Protocol Override: The generated analysis contained potentially hazardous agricultural advice and was blocked. Please consult a local expert."
    else:
        state["compliance_flag"] = "PASS"

    return state

# ==========================================
# Squad 4: Output Synthesis (Translation & Voice)
# ==========================================
def final_translation_node(state: SwarmState):
    # Skip if we already have a translated error from the Gatekeeper
    if state.get("final_translated_text"):
        return state

    english_text = state["agronomist_draft_en"]
    target_lang = state["detected_language"]

    if target_lang != "en":
        state["final_translated_text"] = GoogleTranslator(source='en', target=target_lang).translate(english_text)
    else:
        state["final_translated_text"] = english_text

    return state

def voicebox_node(state: SwarmState):
    # This node accepts either the Gatekeeper's rejection OR the Agronomist's advice
    text_to_speak = state.get("final_translated_text", "Error in pipeline.")
    lang_code = state.get("detected_language", "en")

    try:
        tts = gTTS(text=text_to_speak, lang=lang_code, slow=False)
        output_filename = "swarm_final_audio.mp3"
        tts.save(output_filename)
        state["output_audio_path"] = output_filename
    except Exception as e:
        state["routing_error"] = f"TTS Error: {str(e)}"

    return state

# ==========================================
# The Master Orchestrator: Assembling the Swarm
# ==========================================
# The Supervisor Logic defined
def supervisor_router(state: SwarmState):
    if state.get("routing_error"):
        return "voicebox_agent" # Short-circuit for profanity/OOD
    return "data_orchestrator"  # Proceed to data harvesting

builder = StateGraph(SwarmState)

# Mount all the Agents we built across the cells
builder.add_node("perception_agent", perception_node)
builder.add_node("gatekeeper_agent", gatekeeper_node)
builder.add_node("data_orchestrator", data_orchestrator_node)
builder.add_node("agronomist_agent", agronomist_node)
builder.add_node("compliance_agent", compliance_node)
builder.add_node("translation_agent", final_translation_node)
builder.add_node("voicebox_agent", voicebox_node)

# Map the complex dynamic routing
builder.add_edge(START, "perception_agent")
builder.add_edge("perception_agent", "gatekeeper_agent")

# The Gatekeeper Switch
builder.add_conditional_edges(
    "gatekeeper_agent",
    supervisor_router,
    {"data_orchestrator": "data_orchestrator", "voicebox_agent": "voicebox_agent"}
)

builder.add_edge("data_orchestrator", "agronomist_agent")
builder.add_edge("agronomist_agent", "compliance_agent")
builder.add_edge("compliance_agent", "translation_agent")
builder.add_edge("translation_agent", "voicebox_agent")
builder.add_edge("voicebox_agent", END)

# Compile the final physical pipeline
ultimate_swarm = builder.compile()
print("✅ Swarm Cognitive Core & Assembly Complete. System is primed for ignition.")

from gtts import gTTS
import os

# ==========================================
# Squad 4, Agent 8: The Polyglot Voicebox
# ==========================================
def voicebox_node(state: SwarmState):
    print("🔊 Voicebox Agent: Synthesizing final audio...")

    # 1. Grab the exact text to be spoken
    # If there's an error (like profanity), it speaks the error message instead
    text_to_speak = state.get("final_translated_text")

    # Fallback failsafe if text is completely missing
    if not text_to_speak:
        text_to_speak = "माफ़ करें, सिस्टम में कोई तकनीकी समस्या है।" # "Sorry, system error."

    # 2. Grab the language code (Defaults to 'hi' if something broke)
    lang_code = state.get("detected_language", "hi")

    try:
        # 3. Execute gTTS Synthesis
        # slow=False ensures a natural, conversational speaking pace
        tts = gTTS(text=text_to_speak, lang=lang_code, slow=False)

        # 4. Save to the temporary Colab drive
        output_filename = "/content/swarm_final_audio.mp3"

        # Remove the old file if it exists so we don't play yesterday's advice
        if os.path.exists(output_filename):
            os.remove(output_filename)

        tts.save(output_filename)

        # 5. Lock the physical file path into the Swarm's memory
        state["output_audio_path"] = output_filename
        print("✅ Voicebox Agent: Audio successfully generated!")

    except Exception as e:
        print(f"❌ Voicebox Agent Failed: {str(e)}")
        state["routing_error"] = f"TTS Error: {str(e)}"

    return state

import asyncio
import aiohttp
import json

# ==========================================
# Upgraded Squad 2: Tiered Data Harvesters
# ==========================================

# Harvester 1: Open-Source Weather (Keyless - Works 100%)
async def fetch_weather(session, location_name):
    try:
        geo_url = f"https://geocoding-api.open-meteo.com/v1/search?name={location_name}&count=1"
        async with session.get(geo_url, timeout=5) as geo_res:
            geo_data = await geo_res.json()
            if not geo_data.get("results"): return {"weather": "Location not found."}
            lat, lon = geo_data["results"][0]["latitude"], geo_data["results"][0]["longitude"]

        weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true"
        async with session.get(weather_url, timeout=5) as weather_res:
            w_data = await weather_res.json()
            return {"weather": f"Temp: {w_data['current_weather']['temperature']}°C, Wind: {w_data['current_weather']['windspeed']} km/h"}
    except:
        return {"weather": "Sensors offline. Use seasonal averages."}

# Harvester 2: Mandi Prices (Gov API with Fallback)
async def fetch_market(session, crop_name):
    API_KEY = "YOUR_GOV_API_KEY_HERE" # Get this from data.gov.in
    url = f"https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key={API_KEY}&format=json&filters[commodity]={crop_name.capitalize()}"

    try:
        if API_KEY != "YOUR_GOV_API_KEY_HERE":
            # Tier 1: Real Government API Call
            async with session.get(url, timeout=5) as res:
                if res.status == 200:
                    data = await res.json()
                    price = data['records'][0]['modal_price']
                    return {"market": f"Live Mandi Price for {crop_name}: {price} INR/Quintal"}

        # Tier 2: The Heuristic Fallback (If API key is missing or server is down)
        raise ValueError("API Key missing or server unreachable.")
    except:
        return {"market": f"Live data unavailable for {crop_name}. Assume standard MSP (Minimum Support Price) margins."}

# Harvester 3: Soil Health (Gov Database with Fallback)
async def fetch_soil(session, location_name):
    # The Indian Soil Health Card API requires complex state/district ID mapping.
    # In production, you would map the 'location_name' to a district code first.
    try:
        # Tier 2 Fallback: We simulate a local static database lookup
        # In a real system, this would read from a local CSV of Indian soil profiles
        karnataka_soils = ["Hubballi", "Dharwad", "Belagavi"]
        rajasthan_soils = ["Kota", "Jaipur", "Jodhpur"]

        if location_name in karnataka_soils:
            return {"soil": f"Historical profile for {location_name}: Red/Laterite Soil. High iron, low nitrogen."}
        elif location_name in rajasthan_soils:
            return {"soil": f"Historical profile for {location_name}: Sandy/Alluvial Soil. Low organic carbon, alkaline pH."}
        else:
            return {"soil": f"No specific soil data for {location_name}. Assume general regional baseline."}
    except:
        return {"soil": "Soil database unreachable."}

# ==========================================
# The Data Orchestrator Node
# ==========================================
async def data_orchestrator_node(state: SwarmState):
    entities = state.get("extracted_entities", {})
    location = entities.get("location", "Hubballi")
    crop = entities.get("crop", "General")

    async with aiohttp.ClientSession() as session:
        results = await asyncio.gather(
            fetch_weather(session, location),
            fetch_market(session, crop),
            fetch_soil(session, location)
        )

    fused_data = {}
    for res in results: fused_data.update(res)
    state["harvested_data"] = fused_data

    return state

# ==========================================
# Upgraded Squad 3: The Gap-Reasoning Agronomist
# ==========================================
def agronomist_node(state: SwarmState):
    query = state["english_query"]
    data = state.get("harvested_data", {})
    crop = state.get("extracted_entities", {}).get("crop", "Unknown")

    system_prompt = f"""You are an elite Agricultural AI. You analyze variables strictly from first principles.
    Target Crop: {crop.upper()}

    REAL-TIME SENSORY DATA:
    {data}

    CRITICAL REASONING PROTOCOL:
    1. GAP ANALYSIS: Look closely at the Sensory Data. If any data point says "Unavailable", "Offline", or "Assume standard", you MUST acknowledge this. State that you are relying on foundational agricultural heuristics for that specific variable.
    2. FIRST PRINCIPLES: Connect the variables. How does the specific soil type (or lack thereof) dictate the water required given the current windspeed and temperature?

    Format EXACTLY like this:
    1. स्थिति का विश्लेषण (Situation Analysis): Briefly explain the data and identify any missing variables.
    2. तुरंत करने योग्य कार्य (Immediate Actions): Step-by-step guidance for the next 48 hours.
    3. दीर्घकालिक देखभाल (Preventive Care): Long-term heuristic advice.
    """

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": query}]

    outputs = reasoning_pipeline(
        messages, max_new_tokens=1024, temperature=0.3, pad_token_id=llm_tokenizer.eos_token_id
    )

    state["agronomist_draft_en"] = outputs[0]["generated_text"][-1]["content"]
    return state

#Optimized update in the architecture for tackling lower connectivity issues
!pip install -q faiss-cpu sentence-transformers

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

# ==========================================
# Squad 2, Agent 4: The Local RAG Archivist
# ==========================================
print("📚 Spinning up the Local RAG Archivist...")

# 1. Load the open-source, offline embedding model
embedder = SentenceTransformer('all-MiniLM-L6-v2', device='cpu')

# 2. The Authorized Knowledge Base (Simulating ICAR / KVK Contingency Plans)
# In production, this would be thousands of rows loaded from a local CSV of ICAR guidelines.
icar_knowledge_base = [
    "ICAR Contingency Kota: If monsoon is delayed by 15 days, avoid sowing Cotton. Shift to short-duration Maize or Blackgram.",
    "KVK Hubballi Soil Guideline: Black cotton soil in this region is highly prone to cracking. Maintain moisture through mulching.",
    "National Pest Advisory: For Pink Bollworm in Cotton, install pheromone traps at 5 per acre. Do not spray synthetic pyrethroids early in the season.",
    "General ICAR Policy: Minimum Support Price (MSP) crops should prioritize organic fertilizers for the first 30 days to establish root health.",
    "Dharwad Moisture Stress: If rainfall is below 50mm in July, implement foliar spray of 2% KNO3 to prevent flower drop."
]

# 3. Vectorize the knowledge base
print("🔢 Vectorizing ICAR Knowledge Base...")
kb_embeddings = embedder.encode(icar_knowledge_base)

# 4. Build the FAISS Index (The mathematical search grid)
dimension = kb_embeddings.shape[1]
rag_index = faiss.IndexFlatL2(dimension)
rag_index.add(np.array(kb_embeddings))

# 5. The Retrieval Function
async def fetch_local_rag(query: str):
    try:
        # Convert the farmer's specific query into a vector
        query_vector = embedder.encode([query])

        # Search the local DB for the top 2 most mathematically relevant guidelines
        distances, indices = rag_index.search(np.array(query_vector), k=2)

        retrieved_texts = [icar_knowledge_base[i] for i in indices[0]]
        return {"local_rag_context": " | ".join(retrieved_texts)}
    except Exception as e:
        return {"local_rag_context": "Offline RAG currently unavailable."}

print("✅ Offline RAG Archivist is locked and loaded.")

# ==========================================
# Upgraded Squad 2: The Orchestrator (APIs + RAG)
# ==========================================
async def data_orchestrator_node(state: SwarmState):
    entities = state.get("extracted_entities", {})
    location = entities.get("location", "Hubballi")
    crop = entities.get("crop", "General")
    query = state.get("english_query", "")

    # Fire the Live APIs AND the Local RAG simultaneously
    async with aiohttp.ClientSession() as session:
        results = await asyncio.gather(
            fetch_weather(session, location),
            fetch_market(session, crop),
            fetch_soil(session, location),
            fetch_local_rag(query) # <-- NEW: Injecting the RAG lookup
        )

    fused_data = {}
    for res in results:
        fused_data.update(res)

    state["harvested_data"] = fused_data
    return state

import time
from typing import TypedDict, Dict, Any, Optional, List

# ==========================================
# 1. The Auditable State Blueprint
# ==========================================
class SwarmState(TypedDict):
    # ... (All previous fields remain exactly the same) ...
    user_audio_path: str
    detected_language: str
    native_transcript: str
    english_query: str
    extracted_entities: dict
    harvested_data: Dict[str, Any]
    agronomist_draft_en: str
    compliance_flag: str
    final_translated_text: str
    output_audio_path: str
    routing_error: Optional[str]

    # 🛡️ THE NEW IMMUTABLE LEDGER
    audit_ledger: List[Dict[str, Any]]

# ==========================================
# 2. The Micro-Logger Utility
# ==========================================
def stamp_ledger(agent_name: str, action: str, internal_logic: str, data_snapshot: Any) -> dict:
    """Creates a standardized, timestamped audit receipt for an agent."""
    return {
        "timestamp": time.strftime('%Y-%m-%d %H:%M:%S', time.localtime()),
        "agent": agent_name,
        "action_taken": action,
        "internal_logic_used": internal_logic,
        "data_snapshot": data_snapshot
    }

# ==========================================
# Upgraded Agent: The Semantic Gatekeeper
# ==========================================
def gatekeeper_node(state: SwarmState):
    query = state["english_query"]
    policy_labels = ["agricultural question", "profanity", "out of domain"]
    classification = policy_classifier(query, policy_labels)
    top_label = classification['labels'][0]

    # Initialize the ledger if it doesn't exist
    current_ledger = state.get("audit_ledger", [])

    if top_label == "profanity":
        state["routing_error"] = "PROFANITY_DETECTED"
        # ... translation logic ...
        logic_rationale = f"DeBERTa Confidence: {classification['scores'][0]:.2f}. Blocked."
    elif top_label == "out of domain":
        state["routing_error"] = "OUT_OF_DOMAIN"
        # ... translation logic ...
        logic_rationale = f"DeBERTa Confidence: {classification['scores'][0]:.2f}. Blocked."
    else:
        state["routing_error"] = None
        logic_rationale = f"DeBERTa Confidence: {classification['scores'][0]:.2f}. Approved for Swarm."

    # 🛡️ AUDIT STAMP: Log the decision
    receipt = stamp_ledger("Gatekeeper_Agent", "Semantic Triage", logic_rationale, top_label)
    state["audit_ledger"] = current_ledger + [receipt]

    return state

# ==========================================
# Upgraded Agent: The Data Orchestrator
# ==========================================
async def data_orchestrator_node(state: SwarmState):
    # ... (Your existing async fetching logic here for Weather, Mandi, Soil, RAG) ...
    # Assume `fused_data` is generated as before.

    state["harvested_data"] = fused_data

    # 🛡️ AUDIT STAMP: Log the raw data fetched before the LLM sees it
    receipt = stamp_ledger(
        "Data_Orchestrator",
        "Async Parallel Fetch",
        "Fired Open-Meteo, Mandi API, and Local FAISS RAG concurrently.",
        fused_data # We save the exact JSON returned by the APIs
    )
    state["audit_ledger"] = state.get("audit_ledger", []) + [receipt]

    return state

# ==========================================
# Upgraded Agent: The Policy Auditor
# ==========================================
def compliance_node(state: SwarmState):
    draft = state["agronomist_draft_en"]
    labels = ["safe farming advice", "hazardous practices"]
    classification = policy_classifier(draft, labels)
    top_label = classification['labels'][0]

    if top_label == "hazardous practices":
        state["compliance_flag"] = "FAIL"
        logic = "Detected potential recommendation of banned chemicals or stubble burning."
        # ... override logic ...
    else:
        state["compliance_flag"] = "PASS"
        logic = "LLM draft passed all agricultural safety guardrails."

    # 🛡️ AUDIT STAMP: Log the safety check
    receipt = stamp_ledger("Compliance_Agent", "Safety Audit", logic, top_label)
    state["audit_ledger"] = state.get("audit_ledger", []) + [receipt]

    return state

# Print the Immutable Audit Ledger
print("\n" + "🛡️ "*20)
print("SYSTEM AUDIT LEDGER:")
for entry in final_state.get('audit_ledger', []):
    print(f"\n🕒 {entry['timestamp']} | 🤖 {entry['agent']}")
    print(f"   ▶ Action: {entry['action_taken']}")
    print(f"   ▶ Logic:  {entry['internal_logic_used']}")
    print(f"   ▶ Data:   {entry['data_snapshot']}")
print("Success")

import sqlite3
import json
import time
import os

# ==========================================
# 1. Hardware-Optimized SQLite Initialization
# ==========================================
DB_PATH = '/content/drive/MyDrive/AgriTech_Swarm_Cache/swarm_audit.db'

def setup_database():
    print("🗄️ Initializing Local SQLite Audit Database...")
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    # Create the immutable ledger table
    c.execute('''CREATE TABLE IF NOT EXISTS system_audits (
                    session_id TEXT PRIMARY KEY,
                    timestamp TEXT,
                    farmer_query TEXT,
                    english_report TEXT,
                    raw_json_ledger TEXT
                 )''')
    conn.commit()
    conn.close()
    print("✅ Database ready for logging.")

setup_database()

# ==========================================
# Upgraded Squad 4: The Audit Compiler Agent
# ==========================================
def audit_compiler_node(state: SwarmState):
    print("📝 Audit Compiler: Generating basic English session report...")

    ledger = state.get("audit_ledger", [])
    query = state.get("english_query", "Unknown Query")
    session_id = f"SESSION_{int(time.time())}"
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())

    # 1. Draft the Basic English Master Report
    report = f"🌾 SWARM AUDIT REPORT | {session_id}\n"
    report += f"Time: {timestamp}\n"
    report += "-"*50 + "\n"
    report += f"🗣️ Farmer's Native Query: {state.get('native_transcript', 'N/A')}\n"
    report += f"🇬🇧 Translated English Target: {query}\n"
    report += "-"*50 + "\n\n"

    report += "🔍 AGENT DECISION LOG:\n"
    for entry in ledger:
        report += f"▶ [{entry['agent']}] at {entry['timestamp']}:\n"
        report += f"   - Action: {entry['action_taken']}\n"
        report += f"   - Logic:  {entry['internal_logic_used']}\n\n"

    report += "-"*50 + "\n"
    report += f"🎯 FINAL SYSTEM OUTPUT (Translated back to farmer):\n{state.get('final_translated_text', 'Pipeline Error')}\n"

    # 2. Hardware-Optimized Database Registration
    try:
        conn = sqlite3.connect(DB_PATH)
        c = conn.cursor()
        c.execute("INSERT INTO system_audits VALUES (?, ?, ?, ?, ?)",
                  (session_id, timestamp, query, report, json.dumps(ledger)))
        conn.commit()
        conn.close()

        # 3. Save a physical text file for easy manual reading
        txt_path = f"/content/drive/MyDrive/AgriTech_Swarm_Cache/{session_id}.txt"
        with open(txt_path, "w", encoding="utf-8") as f:
            f.write(report)

        print(f"💾 Audit successfully archived to SQLite and saved as {session_id}.txt")
    except Exception as e:
        print(f"⚠️ Audit Storage Failed: {e}")
        state["routing_error"] = f"Database Error: {str(e)}"

    return state

# ... (Previous node mounting) ...
builder.add_node("audit_compiler", audit_compiler_node) # Mount the new agent
builder.add_node("voicebox_agent", voicebox_node)

# ... (Previous edge routing) ...
builder.add_edge("compliance_agent", "translation_agent")

# The New End-of-Line Flow
builder.add_edge("translation_agent", "audit_compiler")
builder.add_edge("audit_compiler", "voicebox_agent")
builder.add_edge("voicebox_agent", END)

ultimate_swarm = builder.compile()
print("✅ Swarm fully assembled with SQLite Audit Compiler.")

# ==========================================
# The Master Orchestrator: Final Swarm Assembly
# ==========================================

# 1. Wipe the old blueprint and start fresh
builder = StateGraph(SwarmState)

# 2. Mount ALL 8 Agents to the new factory floor
builder.add_node("perception_agent", perception_node)
builder.add_node("gatekeeper_agent", gatekeeper_node)
builder.add_node("data_orchestrator", data_orchestrator_node)
builder.add_node("agronomist_agent", agronomist_node)
builder.add_node("compliance_agent", compliance_node)
builder.add_node("translation_agent", final_translation_node)
builder.add_node("audit_compiler", audit_compiler_node)       # <-- The New SQLite Agent
builder.add_node("voicebox_agent", voicebox_node)

# 3. Wire the Dynamic Routing
builder.add_edge(START, "perception_agent")
builder.add_edge("perception_agent", "gatekeeper_agent")

# The Gatekeeper Switch
builder.add_conditional_edges(
    "gatekeeper_agent",
    supervisor_router,
    {"data_orchestrator": "data_orchestrator", "voicebox_agent": "voicebox_agent"}
)

# The Core Cognitive Pipeline
builder.add_edge("data_orchestrator", "agronomist_agent")
builder.add_edge("agronomist_agent", "compliance_agent")
builder.add_edge("compliance_agent", "translation_agent")

# The End-of-Line Pipeline
builder.add_edge("translation_agent", "audit_compiler")       # Translates, then passes to Auditor
builder.add_edge("audit_compiler", "voicebox_agent")          # Auditor logs it, then passes to Voicebox
builder.add_edge("voicebox_agent", END)

# 4. Lock and Compile the V8 Final Architecture
ultimate_swarm = builder.compile()
print("✅ Swarm Blueprint wiped, rebuilt, and compiled perfectly with the SQLite Auditor.")

import time
from IPython.display import Audio, display

# ==========================================
# 1. The Pristine Swarm State Initialization
# ==========================================
initial_state = {
    "user_audio_path": "/content/sample_audio_3.mp3.mpeg",
    "detected_language": "",
    "native_transcript": "",
    "english_query": "",
    # We pass explicit entities here to simulate our micro-extractor for the prototype
    "extracted_entities": {"location": "Kota", "crop": "Cotton"},
    "harvested_data": {},
    "agronomist_draft_en": "",
    "compliance_flag": "",
    "final_translated_text": "",
    "output_audio_path": "",
    "routing_error": None,
    "audit_ledger": [] # Start with a completely blank cryptographic ledger
}

print("🚀 INITIATING MULTI-AGENT SWARM SEQUENCE (V8)")
print("="*65)
print("⏳ Processing asynchronous cognitive matrix... Please wait.\n")

# ==========================================
# 2. Trigger the Asynchronous Swarm
# ==========================================
try:
    start_time = time.time()

    # Fire the async invoke command to unlock parallel data harvesting
    final_state = await ultimate_swarm.ainvoke(initial_state)

    end_time = time.time()

    # ==========================================
    # 3. The Command Center Dashboard Output
    # ==========================================
    print("✅ SWARM EXECUTION COMPLETE")
    print(f"⏱️ Total System Latency: {end_time - start_time:.2f} seconds")
    print("="*65)

    print(f"🎙️ 1. Native Perception:    {final_state.get('native_transcript', 'N/A')} ({final_state.get('detected_language', 'N/A')})")
    print(f"🇬🇧 2. English Core:         {final_state.get('english_query', 'N/A')}")

    # Check if the Gatekeeper short-circuited the graph
    if final_state.get('routing_error'):
         print(f"⛔ 3. Gatekeeper Status:    BLOCKED -> {final_state.get('routing_error')}")
    else:
         print("🛡️ 3. Gatekeeper Status:    APPROVED (Agricultural Intent Verified)")
         print("📡 4. Data Harvesters:      Weather, Market, & RAG Fused Concurrently")
         print(f"✅ 5. Policy Auditor:       {final_state.get('compliance_flag', 'N/A')} (Strict Safety Adherence)")

    print("\n🧠 6. Final Swarm Output (Translated to Native):\n")
    print(final_state.get('final_translated_text', 'N/A'))
    print("="*65)

    # ==========================================
    # 4. Interface Generation & Audit Hand-off
    # ==========================================
    # Display the audio player so you can hear the TTS output
    if final_state.get('output_audio_path'):
        print("\n🔊 Voicebox Output Ready:")
        display(Audio(final_state['output_audio_path'], autoplay=True))

    # Print the micro-ledger to the console
    print("\n🗄️ Audit Trail Micro-Summary:")
    for entry in final_state.get('audit_ledger', []):
        print(f"   ▶ [{entry['agent']}] -> {entry['action_taken']}")

    print("\n(Full detailed English report securely registered to local SQLite Database)")

except Exception as e:
    print(f"\n❌ FATAL SWARM CRASH: {str(e)}")

# Add this at the very top of your master block to kill the red GPU warnings
from transformers import logging as hf_logging
hf_logging.set_verbosity_error()

# ==========================================
# Upgraded Agent: The Complete Data Orchestrator
# ==========================================
async def data_orchestrator_node(state: SwarmState):
    print("📡 Data Orchestrator: Firing parallel network & RAG requests...")

    entities = state.get("extracted_entities", {})
    location = entities.get("location", "Hubballi")
    crop = entities.get("crop", "General")
    query = state.get("english_query", "")

    # 1. Fire the Live APIs AND the Local FAISS RAG simultaneously
    async with aiohttp.ClientSession() as session:
        results = await asyncio.gather(
            fetch_weather(session, location),
            fetch_market(session, crop),
            fetch_soil(session, location),
            fetch_local_rag(query)
        )

    # 2. Compile the data mathematically
    fused_data = {}
    for res in results:
        fused_data.update(res)

    state["harvested_data"] = fused_data

    # 3. 🛡️ AUDIT STAMP: Log the raw data fetched before the LLM sees it
    receipt = stamp_ledger(
        "Data_Orchestrator",
        "Async Parallel Fetch",
        "Fired Open-Meteo, Mandi API, and Local FAISS RAG concurrently.",
        fused_data # We save the exact JSON returned by the APIs
    )
    state["audit_ledger"] = state.get("audit_ledger", []) + [receipt]

    return state

# ==============================================================================
# 🌾 AGRITECH MULTI-AGENT SWARM: V9 MASTER ARCHITECTURE (UNIFIED)
# ==============================================================================
import os
import time
import json
import asyncio
import aiohttp
import sqlite3
import warnings
import faiss
import numpy as np
import torch
import re

from deep_translator import GoogleTranslator
from gtts import gTTS
from typing import TypedDict, Dict, Any, Optional, List
from IPython.display import Audio, display

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline
from transformers import logging as hf_logging
from faster_whisper import WhisperModel
from sentence_transformers import SentenceTransformer
from langgraph.graph import StateGraph, START, END

# Mute harmless warnings
warnings.filterwarnings("ignore")
hf_logging.set_verbosity_error()

# ==========================================
# PHASE 1: SYSTEM CACHE & DATABASES
# ==========================================
print("🔗 [1/4] Initializing Storage, Cache & Databases...")
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
CACHE_DIR = '/content/drive/MyDrive/AgriTech_Swarm_Cache'
os.makedirs(CACHE_DIR, exist_ok=True)
os.environ['HF_HOME'] = CACHE_DIR
os.environ['TORCH_HOME'] = CACHE_DIR

# 1A. Initialize SQLite Audit Database
DB_PATH = f'{CACHE_DIR}/swarm_audit.db'
conn = sqlite3.connect(DB_PATH)
conn.cursor().execute('''CREATE TABLE IF NOT EXISTS system_audits (
                session_id TEXT PRIMARY KEY, timestamp TEXT, farmer_query TEXT,
                english_report TEXT, raw_json_ledger TEXT)''')
conn.commit()
conn.close()

# 1B. Initialize FAISS Local RAG Database
embedder = SentenceTransformer('all-MiniLM-L6-v2', device='cpu')
icar_knowledge_base = [
    "ICAR Contingency Kota: If monsoon is delayed by 15 days, avoid sowing Cotton. Shift to short-duration Maize.",
    "KVK Hubballi Soil Guideline: Black cotton soil in this region is highly prone to cracking. Maintain moisture through mulching.",
    "National Pest Advisory: For Pink Bollworm in Cotton, install pheromone traps at 5 per acre. Do not spray synthetic pyrethroids early.",
    "General ICAR Policy: Minimum Support Price (MSP) crops should prioritize organic fertilizers for the first 30 days.",
    "Dharwad Moisture Stress: If rainfall is below 50mm in July, implement foliar spray of 2% KNO3."
]
kb_embeddings = embedder.encode(icar_knowledge_base)
rag_index = faiss.IndexFlatL2(kb_embeddings.shape[1])
rag_index.add(np.array(kb_embeddings))

# ==========================================
# PHASE 2: CORE COGNITIVE ENGINES
# ==========================================
print("🧠 [2/4] Waking Neural Engines (Whisper, Qwen, DeBERTa)...")
audio_model = WhisperModel("large-v3-turbo", device="cuda", compute_type="float16", download_root=CACHE_DIR)
quantization_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16, bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True)
llm_tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct")
llm_model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2.5-7B-Instruct", quantization_config=quantization_config, device_map="auto")
reasoning_pipeline = pipeline("text-generation", model=llm_model, tokenizer=llm_tokenizer, device_map="auto")
policy_classifier = pipeline("zero-shot-classification", model="MoritzLaurer/DeBERTa-v3-base-zeroshot-v2.0", device="cuda")

# ==========================================
# PHASE 3: SWARM BLUEPRINT & UTILITIES
# ==========================================
class SwarmState(TypedDict):
    user_audio_path: str
    detected_language: str
    native_transcript: str
    english_query: str
    extracted_entities: dict
    harvested_data: Dict[str, Any]
    agronomist_draft_en: str
    compliance_flag: str
    final_translated_text: str
    output_audio_path: str
    routing_error: Optional[str]
    audit_ledger: List[Dict[str, Any]]

def stamp_ledger(agent_name: str, action: str, logic: str, data: Any) -> dict:
    return {"timestamp": time.strftime('%Y-%m-%d %H:%M:%S', time.localtime()), "agent": agent_name, "action_taken": action, "internal_logic_used": logic, "data_snapshot": data}

# ==========================================
# PHASE 4: AGENT SQUADS (THE NODES)
# ==========================================
print("🤖 [3/4] Assembling Multi-Agent Squads...")

# Agent 1: Perception
def perception_node(state: SwarmState):
    segments, info = audio_model.transcribe(state["user_audio_path"], beam_size=5)
    native_text = " ".join([s.text for s in segments])
    lang = "hi" if info.language == "ur" else info.language
    english_text = GoogleTranslator(source=lang, target='en').translate(native_text) if lang != "en" else native_text

    state.update({"detected_language": lang, "native_transcript": native_text, "english_query": english_text})
    return state

# Agent 2: Gatekeeper
def gatekeeper_node(state: SwarmState):
    classification = policy_classifier(state["english_query"], ["agricultural question", "profanity", "out of domain"])
    top_label = classification['labels'][0]

    if top_label == "profanity":
        state["routing_error"] = "PROFANITY_DETECTED"
        state["final_translated_text"] = GoogleTranslator(source='en', target=state["detected_language"]).translate("Please use respectful language.")
    elif top_label == "out of domain":
        state["routing_error"] = "OUT_OF_DOMAIN"
        state["final_translated_text"] = GoogleTranslator(source='en', target=state["detected_language"]).translate("I am an agricultural expert. Ask farming questions.")
    else:
        state["routing_error"] = None

    state["audit_ledger"] = state.get("audit_ledger", []) + [stamp_ledger("Gatekeeper", "Triage", f"Confidence {classification['scores'][0]:.2f}", top_label)]
    return state

# Async Harvesters
async def fetch_weather(session, loc):
    try:
        async with session.get(f"https://geocoding-api.open-meteo.com/v1/search?name={loc}&count=1", timeout=5) as r:
            geo = await r.json()
            if not geo.get("results"): return {"weather": "Location not found."}
            lat, lon = geo["results"][0]["latitude"], geo["results"][0]["longitude"]
        async with session.get(f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true", timeout=5) as r:
            w = await r.json()
            return {"weather": f"Temp: {w['current_weather']['temperature']}°C, Wind: {w['current_weather']['windspeed']} km/h"}
    except: return {"weather": "Sensors offline. Use seasonal averages."}

async def fetch_market(session, crop):
    await asyncio.sleep(0.5)
    return {"market": f"Approx 2,450 INR/Quintal" if crop.lower() != "general" else "No crop specified."}

async def fetch_soil(session, loc):
    await asyncio.sleep(0.6)
    return {"soil": f"Profile for {loc}: Black Cotton Soil. N: Deficient. P: Medium." if loc in ["Hubballi", "Kota"] else "Assume regional baseline."}

async def fetch_local_rag(query):
    vec = embedder.encode([query])
    _, indices = rag_index.search(np.array(vec), k=2)
    return {"local_rag_context": " | ".join([icar_knowledge_base[i] for i in indices[0]])}

# Agent 3: Data Orchestrator
async def data_orchestrator_node(state: SwarmState):
    loc, crop, query = state.get("extracted_entities", {}).get("location", "Hubballi"), state.get("extracted_entities", {}).get("crop", "General"), state.get("english_query", "")
    async with aiohttp.ClientSession() as session:
        res = await asyncio.gather(fetch_weather(session, loc), fetch_market(session, crop), fetch_soil(session, loc), fetch_local_rag(query))

    fused = {}
    for r in res: fused.update(r)
    state["harvested_data"] = fused
    state["audit_ledger"] = state.get("audit_ledger", []) + [stamp_ledger("Data_Orchestrator", "Async Fetch", "Fired APIs & Local RAG", fused)]
    return state

# Agent 4: Agronomist Brain
def agronomist_node(state: SwarmState):
    prompt = f"Elite Agronomist AI. Crop: {state.get('extracted_entities', {}).get('crop', 'Unknown')}\nDATA: {state.get('harvested_data', {})}\nPROTOCOL: Do Gap Analysis if data is offline. Connect variables. Give [SITUATION METRICS], [SYSTEMIC ANALYSIS], and [ACTIONABLE DIRECTIVES]."
    out = reasoning_pipeline([{"role": "system", "content": prompt}, {"role": "user", "content": state["english_query"]}], max_new_tokens=1024, temperature=0.3, pad_token_id=llm_tokenizer.eos_token_id)
    state["agronomist_draft_en"] = out[0]["generated_text"][-1]["content"]
    return state

# Agent 5: Compliance Auditor
def compliance_node(state: SwarmState):
    draft = state["agronomist_draft_en"]
    label = policy_classifier(draft, ["safe farming advice", "hazardous practices"])['labels'][0]
    if label == "hazardous practices":
        state.update({"compliance_flag": "FAIL", "agronomist_draft_en": "Safety Override: Hazardous advice blocked."})
    else: state["compliance_flag"] = "PASS"
    state["audit_ledger"] = state.get("audit_ledger", []) + [stamp_ledger("Compliance_Auditor", "Safety Scan", "Checked for banned chemicals", label)]
    return state

# Agent 6: Translator
def final_translation_node(state: SwarmState):
    if not state.get("final_translated_text"):
        state["final_translated_text"] = GoogleTranslator(source='en', target=state["detected_language"]).translate(state["agronomist_draft_en"]) if state["detected_language"] != "en" else state["agronomist_draft_en"]
    return state

# Agent 7: Audit Compiler
def audit_compiler_node(state: SwarmState):
    sid = f"SESSION_{int(time.time())}"
    report = f"🌾 SWARM AUDIT | {sid}\nTarget: {state['english_query']}\n"
    for e in state.get("audit_ledger", []): report += f"[{e['agent']}] {e['action_taken']} -> {e['internal_logic_used']}\n"
    report += f"\nFINAL OUT: {state.get('final_translated_text', 'N/A')}"

    try:
        conn = sqlite3.connect(DB_PATH)
        conn.cursor().execute("INSERT INTO system_audits VALUES (?, ?, ?, ?, ?)", (sid, time.strftime('%Y-%m-%d %H:%M:%S'), state['english_query'], report, json.dumps(state.get("audit_ledger", []))))
        conn.commit()
        conn.close()
        with open(f"{CACHE_DIR}/{sid}.txt", "w", encoding="utf-8") as f: f.write(report)
    except: pass
    return state

# Agent 8: Voicebox
def voicebox_node(state: SwarmState):
    try:
        tts = gTTS(text=state.get("final_translated_text", "Error."), lang=state.get("detected_language", "hi"), slow=False)
        out_path = "/content/swarm_final_audio.mp3"
        if os.path.exists(out_path): os.remove(out_path)
        tts.save(out_path)
        state["output_audio_path"] = out_path
    except: state["routing_error"] = "TTS Error"
    return state

# ==========================================
# PHASE 5: GRAPH ASSEMBLY & COMPILATION
# ==========================================
def supervisor_router(state: SwarmState):
    return "voicebox_agent" if state.get("routing_error") else "data_orchestrator"

builder = StateGraph(SwarmState)
for n in [("perception", perception_node), ("gatekeeper", gatekeeper_node), ("data_orchestrator", data_orchestrator_node), ("agronomist", agronomist_node), ("compliance", compliance_node), ("translation", final_translation_node), ("audit", audit_compiler_node), ("voicebox", voicebox_node)]: builder.add_node(f"{n[0]}_agent", n[1])

builder.add_edge(START, "perception_agent")
builder.add_edge("perception_agent", "gatekeeper_agent")
builder.add_conditional_edges("gatekeeper_agent", supervisor_router, {"data_orchestrator": "data_orchestrator_agent", "voicebox_agent": "voicebox_agent"})
builder.add_edge("data_orchestrator_agent", "agronomist_agent")
builder.add_edge("agronomist_agent", "compliance_agent")
builder.add_edge("compliance_agent", "translation_agent")
builder.add_edge("translation_agent", "audit_agent")
builder.add_edge("audit_agent", "voicebox_agent")
builder.add_edge("voicebox_agent", END)

ultimate_swarm = builder.compile()
print("✅ [4/4] Ultimate Swarm Compiled. System is locked and loaded.")

# ==========================================
# PHASE 6: COMMAND CENTER IGNITION
# ==========================================
initial_state = {
    "user_audio_path": "/content/sample_audio_3.mp3", # <--- UPDATE THIS TO YOUR CURRENT AUDIO FILE NAME!
    "detected_language": "", "native_transcript": "", "english_query": "",
    "extracted_entities": {"location": "Kota", "crop": "Cotton"}, "harvested_data": {},
    "agronomist_draft_en": "", "compliance_flag": "", "final_translated_text": "",
    "output_audio_path": "", "routing_error": None, "audit_ledger": []
}

print("\n🚀 INITIATING V9 MULTI-AGENT SWARM...")
print("="*65)
try:
    start_time = time.time()
    final_state = await ultimate_swarm.ainvoke(initial_state)

    print(f"✅ EXECUTION COMPLETE | Latency: {time.time() - start_time:.2f}s")
    print("="*65)
    print(f"🎙️ 1. Native:        {final_state.get('native_transcript')} ({final_state.get('detected_language')})")
    print(f"🇬🇧 2. English:       {final_state.get('english_query')}")

    if final_state.get('routing_error'):
         print(f"⛔ 3. Gatekeeper:    BLOCKED -> {final_state.get('routing_error')}")
    else:
         print("🛡️ 3. Gatekeeper:    APPROVED")
         print("📡 4. Data Harvester: Weather, Market, & RAG Fused")
         print(f"✅ 5. Compliance:    {final_state.get('compliance_flag')} (Safe)")

    print(f"\n🧠 6. Final Swarm Output:\n{final_state.get('final_translated_text')}")
    print("="*65)

    if final_state.get('output_audio_path'):
        print("\n🔊 Voicebox Ready:")
        display(Audio(final_state['output_audio_path'], autoplay=True))
    print("\n🗄️ (Detailed report securely registered to local SQLite Database)")
except Exception as e: print(f"\n❌ FATAL CRASH: {str(e)}")