# -*- coding: utf-8 -*-
"""AgriAdvice - Original.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yCPL9pLu2Us8Vbio-b7lutVG5RG3gDr
"""

import os
from google.colab import drive

# ==========================================
# Phase 1: Storage & Cache Architecture
# ==========================================
print("🔗 Mounting Google Drive...")
# This will prompt a Google popup asking for permission to access your Drive.
drive.mount('/content/drive')

# We create a dedicated, isolated folder in your Drive so it doesn't clutter your personal files
CACHE_DIR = '/content/drive/MyDrive/AI_Prototype_Cache'
os.makedirs(CACHE_DIR, exist_ok=True)

# We brutally redirect the system's default download paths to your Drive
os.environ['HF_HOME'] = CACHE_DIR
os.environ['TORCH_HOME'] = CACHE_DIR

print(f"📁 Cache successfully redirected to: {CACHE_DIR}")

# ==========================================
# Phase 2: Infrastructure Dependencies
# ==========================================
print("⚙️ Installing system tools... (This only takes a few seconds)")
!pip install -q langgraph transformers==4.46.1 accelerate bitsandbytes faster-whisper langchain langchain-community sentence-transformers faiss-cpu requests>=2.32.5
!pip install -q git+https://github.com/huggingface/parler-tts.git

# ==========================================
# Phase 3: Waking the AI Models
# ==========================================
# Because of Phase 1, these will download to your Google Drive TODAY.
# TOMORROW, they will load instantly from your Drive.

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline
from faster_whisper import WhisperModel
from parler_tts import ParlerTTSForConditionalGeneration

print("🧠 Loading Models into VRAM... (Downloading to Drive first time, loading instantly hereafter)")

# 1. The Ear (Whisper) - Explicitly telling it to save to our Drive folder
audio_model = WhisperModel("large-v3-turbo", device="cuda", compute_type="float16", download_root=CACHE_DIR)

# 2. The Brain (Qwen 7B in 4-bit)
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)
llm_tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct")
llm_model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-7B-Instruct",
    quantization_config=quantization_config,
    device_map="auto"
)
reasoning_pipeline = pipeline("text-generation", model=llm_model, tokenizer=llm_tokenizer, max_new_tokens=256, temperature=0.3)

# 3. The Voicebox (Parler-TTS)
tts_tokenizer = AutoTokenizer.from_pretrained("parler-tts/parler-tts-mini-v1")
tts_model = ParlerTTSForConditionalGeneration.from_pretrained("parler-tts/parler-tts-mini-v1").to("cuda")

# 4. The Guardrail (DeBERTa)
policy_classifier = pipeline("zero-shot-classification", model="MoritzLaurer/DeBERTa-v3-base-zeroshot-v2.0", device="cuda")

print("✅ ALL SYSTEMS GO. Architecture successfully cached and loaded!")

# 1. Install LangGraph for stateful agent orchestration
!pip install -q langgraph

# 2. Install the lightweight Guardrail dependencies
!pip install -q transformers optimum # Optimum helps run smaller models faster

# 1. Install LangGraph for the automated state machine
!pip install -q langgraph

# 2. Install AI4Bharat's Indic TTS dependencies (Parler-TTS backend)
!pip install -q git+https://github.com/huggingface/parler-tts.git

# 3. Upgrade Transformers for Qwen2.5 / Llama 3.1 support
!pip install -q --upgrade transformers accelerate bitsandbytes

# Forcing the environment to use the exact version required by the voice model
!pip install -q transformers==4.46.1 protobuf>=5.29.1

from typing import TypedDict, Optional

# We are defining the exact blueprint of our Manager's Clipboard (The State)
class AgenticState(TypedDict):
    user_audio_path: str          # Where the original voice recording is saved
    detected_language: str        # e.g., "hi" for Hindi, "ta" for Tamil, "en" for English
    user_transcript: str          # The text of what the user actually said
    retrieved_context: str        # The data pulled from your background dataset
    draft_response: str           # The AI's initial answer (before safety checks)
    final_safe_response: str      # The approved, policy-checked text
    output_audio_path: str        # Where the final AI voice file is saved
    error_flag: Optional[str]     # A red flag if something goes wrong (like pure static)

print("✅ Blueprint for the Agentic State has been successfully created in memory!")

from faster_whisper import WhisperModel

# 1. We specify the model size
model_size = "large-v3-turbo"

# 2. We explicitly attach it to the GPU ("cuda") and cut its memory size in half ("float16")
audio_model = WhisperModel(model_size, device="cuda", compute_type="float16")

print("✅ The Ear is fully awake, loaded into VRAM, and listening!")

# Downloading the faste whisper module
!pip install -q faster-whisper

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline

# 1. Hardware Optimization: Configure 4-bit quantization to shrink the 7B model from 14GB to ~5GB
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

# 2. Define the Polyglot LLM
model_id = "Qwen/Qwen2.5-7B-Instruct"

# 3. Load the Tokenizer (Text -> Numbers) and the Model (The Neural Network)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=quantization_config,
    device_map="auto"  # Automatically maps the model weights to the GPU
)

# 4. Create the Generation Pipeline to handle the actual reasoning process
reasoning_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=256,  # Hard cap for prototype speed
    temperature=0.3,     # Low temperature forces logical, factual responses over creative ones
)

# 5. Define the actual Node Function that our LangGraph Manager will call
def brain_node(state):
    # Extract the necessary variables from the moving state dictionary
    user_text = state["user_transcript"]
    lang = state["detected_language"]

    # We use a placeholder for context right now until we build the RAG (Retrieval) Node
    context = state.get("retrieved_context", "No background context provided yet.")

    # Dynamically inject the detected language into the system prompt to force the output language
    system_prompt = f"""You are an intelligent reasoning agent.
    The user spoke in language code: '{lang}'.
    Context: {context}

    Answer the user's query using the context.
    CRITICAL: Your final output MUST be written in the exact same language as the user's language code ({lang})."""

    # Format the messages in the standard chat template
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_text}
    ]

    # Generate the reasoning and extract the raw text
    outputs = reasoning_pipeline(messages)
    generated_text = outputs[0]["generated_text"][-1]["content"]

    # Update the state clipboard with the drafted response
    state["draft_response"] = generated_text

    return state

from langchain_community.embeddings import HuggingFaceBgeEmbeddings
from langchain_community.vectorstores import FAISS

# 1. Initialize the Embedding Engine (The Cartographer)
# BAAI/bge-small-en-v1.5 maps text to 384-dimensional vectors.
# It is chosen for its extreme efficiency, leaving VRAM available for the LLM.
embedding_model_name = "BAAI/bge-small-en-v1.5"
embedding_kwargs = {"device": "cuda"} # Hardware acceleration constraint
encode_kwargs = {"normalize_embeddings": True} # Normalizes vectors to length 1 for faster cosine similarity

embeddings = HuggingFaceBgeEmbeddings(
    model_name=embedding_model_name,
    model_kwargs=embedding_kwargs,
    encode_kwargs=encode_kwargs
)

# 2. Establish the Prototypic Substrate (The Dataset)
# For the bare-minimum prototype, we hardcode a small array of contextual data.
# In a production state, this array is populated by a DocumentLoader parsing PDFs/CSVs.
prototypic_dataset = [
    "The multi-modal AI system utilizes Faster-Whisper to transcribe audio inputs into discrete text tokens.",
    "The reasoning architecture relies on a 4-bit quantized Qwen 7B model to operate within the 16GB VRAM constraint of a T4 GPU.",
    "The LangGraph orchestrator acts as a stateful machine, routing data through a defined dictionary blueprint called the AgenticState.",
    "AI4Bharat provides the crucial polyglot dependencies required to synthesize Indian languages accurately."
]

# 3. Construct the Vector Index (The Spatial Database)
# FAISS mathematically indexes the strings against the embedding coordinates in VRAM.
vector_database = FAISS.from_texts(prototypic_dataset, embeddings)

# 4. Instantiate the Retrieval Mechanism
# 'k=2' dictates that the algorithm will only extract the top 2 closest semantic matches to prevent context window overflow.
retriever = vector_database.as_retriever(search_kwargs={"k": 2})

# 5. Define the Node Function (The API for LangGraph)
def researcher_node(state):
    # Extract the transcribed query from the state dictionary
    query = state["user_transcript"]

    # Execute the geometric similarity search against the FAISS index
    retrieved_documents = retriever.invoke(query)

    # Concatenate the retrieved data objects into a continuous string format for LLM ingestion
    context_string = "\n".join([doc.page_content for doc in retrieved_documents])

    # Mutate the state dictionary to include the new context
    state["retrieved_context"] = context_string

    return state

# Downloading the RAG Ecosystem (The Cartographer and the Spatial Database)
# We use -q to keep the installation quiet and clean
!pip install -q langchain langchain-community sentence-transformers faiss-gpu

# Swapping the GPU spatial database for the universally compatible CPU version
!pip install -q langchain langchain-community sentence-transformers faiss-cpu

# Forcing the environment to downgrade 'requests' to exactly what Colab requires
!pip install -q requests==2.32.4

# Prioritizing the AI ecosystem's requirements
!pip install -q requests>=2.32.5

from langchain_community.embeddings import HuggingFaceBgeEmbeddings
from langchain_community.vectorstores import FAISS

# 1. Initialize the Embedding Engine (The Cartographer)
# BAAI/bge-small-en-v1.5 maps text to 384-dimensional vectors.
# It is chosen for its extreme efficiency, leaving VRAM available for the LLM.
embedding_model_name = "BAAI/bge-small-en-v1.5"
embedding_kwargs = {"device": "cuda"} # Hardware acceleration constraint
encode_kwargs = {"normalize_embeddings": True} # Normalizes vectors to length 1 for faster cosine similarity

embeddings = HuggingFaceBgeEmbeddings(
    model_name=embedding_model_name,
    model_kwargs=embedding_kwargs,
    encode_kwargs=encode_kwargs
)

# 2. Establish the Prototypic Substrate (The Dataset)
# For the bare-minimum prototype, we hardcode a small array of contextual data.
# In a production state, this array is populated by a DocumentLoader parsing PDFs/CSVs.
prototypic_dataset = [
    "The multi-modal AI system utilizes Faster-Whisper to transcribe audio inputs into discrete text tokens.",
    "The reasoning architecture relies on a 4-bit quantized Qwen 7B model to operate within the 16GB VRAM constraint of a T4 GPU.",
    "The LangGraph orchestrator acts as a stateful machine, routing data through a defined dictionary blueprint called the AgenticState.",
    "AI4Bharat provides the crucial polyglot dependencies required to synthesize Indian languages accurately."
]

# 3. Construct the Vector Index (The Spatial Database)
# FAISS mathematically indexes the strings against the embedding coordinates in VRAM.
vector_database = FAISS.from_texts(prototypic_dataset, embeddings)

# 4. Instantiate the Retrieval Mechanism
# 'k=2' dictates that the algorithm will only extract the top 2 closest semantic matches to prevent context window overflow.
retriever = vector_database.as_retriever(search_kwargs={"k": 2})

# 5. Define the Node Function (The API for LangGraph)
def researcher_node(state):
    # Extract the transcribed query from the state dictionary
    query = state["user_transcript"]

    # Execute the geometric similarity search against the FAISS index
    retrieved_documents = retriever.invoke(query)

    # Concatenate the retrieved data objects into a continuous string format for LLM ingestion
    context_string = "\n".join([doc.page_content for doc in retrieved_documents])

    # Mutate the state dictionary to include the new context
    state["retrieved_context"] = context_string

    return state

from langgraph.graph import StateGraph, START, END

# 1. Standardize the Ear Interface
# Wraps the acoustic model into a node that strictly interacts with the AgenticState dictionary
def ear_node(state):
    # Retrieve the raw acoustic data path
    audio_path = state["user_audio_path"]

    # Execute the acoustic-to-discrete-token transformation
    segments, info = audio_model.transcribe(audio_path, beam_size=5)

    # Concatenate the token generator object into a continuous string
    full_transcript = " ".join([segment.text for segment in segments])

    # Mutate the state clipboard with the extracted data
    state["detected_language"] = info.language
    state["user_transcript"] = full_transcript

    return state

# 2. Initialize the Orchestrator
# Instantiate the graph with the exact type-hinted dictionary blueprint
workflow = StateGraph(AgenticState)

# 3. Mount the Compute Nodes
# Attach our isolated functions to the graph memory space
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)

# 4. Define the Directed Edges (Routing Logic)
# Establish the sequential, automated flow: Audio -> Semantic Search -> LLM Generation
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", END)

# 5. Compile the Architecture
# Locks the graph topology and optimizes the execution paths in memory
ai_pipeline = workflow.compile()

# 1. Define the Initial State (The Input Vector)
# CRITICAL: Ensure the filename exactly matches the file you uploaded to Colab's sidebar.
initial_state = {
    "user_audio_path": "sample_audio_1.mp3.mpeg",
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("Initiating Pipeline... Listening and Reasoning (This takes 30-60 seconds)")

# 2. Execute the Graph Traversal
# Triggers the automated cascade: Ear -> Researcher -> Brain.
final_state = ai_pipeline.invoke(initial_state)

# 3. Output Extraction
print("\n--- Final Extracted State ---")
print(f"Detected Language: {final_state['detected_language']}")
print(f"Your Transcript:   {final_state['user_transcript']}")
print(f"Retrieved Context: {final_state['retrieved_context']}")
print(f"\nAI Reasoned Output:\n{final_state['draft_response']}")

# 1. Define the Initial State (The Input Vector)
# CRITICAL: Ensure the filename exactly matches the file you uploaded to Colab's sidebar.
initial_state = {
    "user_audio_path": "sample_audio_1.mp3.mpeg",
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("Initiating Pipeline... Listening and Reasoning (This takes 30-60 seconds)")

# 2. Execute the Graph Traversal
# Triggers the automated cascade: Ear -> Researcher -> Brain.
final_state = ai_pipeline.invoke(initial_state)

# 3. Output Extraction
print("\n--- Final Extracted State ---")
print(f"Detected Language: {final_state['detected_language']}")
print(f"Your Transcript:   {final_state['user_transcript']}")
print(f"Retrieved Context: {final_state['retrieved_context']}")
print(f"\nAI Reasoned Output:\n{final_state['draft_response']}")

from langgraph.graph import StateGraph, START, END

# 1. The Patched Ear Interface
def ear_node(state):
    audio_path = state["user_audio_path"]
    segments, info = audio_model.transcribe(audio_path, beam_size=5)
    full_transcript = " ".join([segment.text for segment in segments])

    # --- EDGE CASE OVERRIDE LOGIC ---
    detected_lang = info.language
    # If the acoustic model confuses Hindustani audio for Urdu, force it to Hindi
    if detected_lang == "ur":
        detected_lang = "hi"
    # --------------------------------

    state["detected_language"] = detected_lang
    state["user_transcript"] = full_transcript

    return state

# 2. Re-Initialize the Orchestrator
workflow = StateGraph(AgenticState)

# 3. Mount the Compute Nodes
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)

# 4. Define the Directed Edges
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", END)

# 5. Re-Compile the Architecture
ai_pipeline = workflow.compile()

# 1. Define the Initial State (The Input Vector)
# CRITICAL: Ensure the filename exactly matches the file you uploaded to Colab's sidebar.
initial_state = {
    "user_audio_path": "sample_audio_1.mpeg",
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("Initiating Pipeline... Listening and Reasoning (This takes 30-60 seconds)")

# 2. Execute the Graph Traversal
# Triggers the automated cascade: Ear -> Researcher -> Brain.
final_state = ai_pipeline.invoke(initial_state)

# 3. Output Extraction
print("\n--- Final Extracted State ---")
print(f"Detected Language: {final_state['detected_language']}")
print(f"Your Transcript:   {final_state['user_transcript']}")
print(f"Retrieved Context: {final_state['retrieved_context']}")
print(f"\nAI Reasoned Output:\n{final_state['draft_response']}")

from transformers import pipeline
from langgraph.graph import StateGraph, START, END

# ==========================================
# 1. Initialize the Policy Engine
# ==========================================
# We load a highly optimized, sub-1GB model strictly for classification.
# This runs alongside your 7B LLM without exceeding the 16GB VRAM limit.
policy_classifier = pipeline(
    "zero-shot-classification",
    model="MoritzLaurer/DeBERTa-v3-base-zeroshot-v2.0",
    device="cuda"
)

# ==========================================
# 2. Define the Guardrail Node
# ==========================================
def guardrail_node(state):
    # Retrieve the raw text drafted by the Brain
    drafted_text = state["draft_response"]

    # Define the strict boundaries of our system
    policy_labels = ["safe and helpful", "toxic, hateful, or harmful advice"]

    # Execute the probability matrix scan
    classification = policy_classifier(drafted_text, policy_labels)

    # Extract the label with the highest mathematical confidence
    top_label = classification['labels'][0]

    # The Routing Logic:
    if top_label == "toxic, hateful, or harmful advice":
        # Overwrite the drafted response with a hardcoded safety fallback
        state["final_safe_response"] = "Policy Override: I cannot fulfill this request safely."
        state["error_flag"] = "Safety Violation Triggered"
    else:
        # If safe, promote the draft to the final output pipeline
        state["final_safe_response"] = drafted_text

    return state

# ==========================================
# 3. Re-Architecting the Assembly Line (V3)
# ==========================================
workflow = StateGraph(AgenticState)

# Mount all 4 compute nodes
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)
workflow.add_node("guardrail", guardrail_node) # <- NEW NODE MOUNTED

# Define the new Directed Edges (Routing)
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", "guardrail")        # Brain now hands off to Guardrail
workflow.add_edge("guardrail", END)            # Guardrail is currently the end of the line

# Compile the updated graph
ai_pipeline = workflow.compile()

import torch
import soundfile as sf
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer
from langgraph.graph import StateGraph, START, END

# ==========================================
# 1. Initialize the Acoustic Synthesizer
# ==========================================
# We load a lightweight TTS model into the remaining GPU memory.
# (Using the highly stable mini-v1 which supports conditional voice prompting)
tts_model_name = "parler-tts/parler-tts-mini-v1"
tts_tokenizer = AutoTokenizer.from_pretrained(tts_model_name)
tts_model = ParlerTTSForConditionalGeneration.from_pretrained(tts_model_name).to("cuda")

# ==========================================
# 2. Define the Voicebox Node
# ==========================================
def voicebox_node(state):
    # Extract the finalized, policy-cleared text
    text_to_speak = state["final_safe_response"]

    # We define the acoustic style (this can be dynamically altered later)
    voice_description = "A clear, professional female voice speaking at a moderate pace with a neutral tone."

    # Tokenize both the style prompt and the actual text
    input_ids = tts_tokenizer(voice_description, return_tensors="pt").input_ids.to("cuda")
    prompt_input_ids = tts_tokenizer(text_to_speak, return_tensors="pt").input_ids.to("cuda")

    # Generate the raw audio waveform
    generation = tts_model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
    audio_waveform = generation.cpu().numpy().squeeze()

    # Save the waveform to the Colab hard drive as a .wav file
    output_filename = "ai_final_response.wav"
    sf.write(output_filename, audio_waveform, tts_model.config.sampling_rate)

    # Mutate the state with the final physical file path
    state["output_audio_path"] = output_filename

    return state

# ==========================================
# 3. The Final Architecture Assembly (V4)
# ==========================================
workflow = StateGraph(AgenticState)

# Mount all 5 compute nodes
workflow.add_node("ear", ear_node)
workflow.add_node("researcher", researcher_node)
workflow.add_node("brain", brain_node)
workflow.add_node("guardrail", guardrail_node)
workflow.add_node("voicebox", voicebox_node) # <- THE FINAL NODE

# Define the complete closed-loop routing
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "researcher")
workflow.add_edge("researcher", "brain")
workflow.add_edge("brain", "guardrail")
workflow.add_edge("guardrail", "voicebox")   # Cleared text goes to the Voicebox
workflow.add_edge("voicebox", END)           # The audio file is the final physical output

# Compile the Master Graph
ai_pipeline = workflow.compile()

from IPython.display import Audio, display

# 1. The Blank Input Vector
initial_state = {
    "user_audio_path": "sample_audio_2.mpeg", # Your uploaded voice clip
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("🚀 INITIATING FULL MASTER PIPELINE...")
print("Nodes executing: Ear -> Researcher -> Brain -> Guardrail -> Voicebox")

# 2. Trigger the Automated Assembly Line
final_state = ai_pipeline.invoke(initial_state)

# 3. Display the final systemic outputs
print("\n" + "="*50)
print(f"✅ Language Detected: {final_state['detected_language']}")
print(f"✅ User Transcript:   {final_state['user_transcript']}")
print(f"✅ Guardrail Cleared: {final_state['final_safe_response']}")
print("="*50)

# 4. Generate the Audio Interface
print("\n🔊 AI Audio Output:")
display(Audio(final_state['output_audio_path'], autoplay=True))

from IPython.display import Audio, display

# 1. The Blank Input Vector
initial_state = {
    "user_audio_path": "sample_audio_2.mpeg", # Your uploaded voice clip
    "detected_language": "",
    "user_transcript": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("🚀 INITIATING FULL MASTER PIPELINE...")
print("Nodes executing: Ear -> Researcher -> Brain -> Guardrail -> Voicebox")

# 2. Trigger the Automated Assembly Line
final_state = ai_pipeline.invoke(initial_state)

# 3. Display the final systemic outputs
print("\n" + "="*50)
print(f"✅ Language Detected: {final_state['detected_language']}")
print(f"✅ User Transcript:   {final_state['user_transcript']}")
print(f"✅ Guardrail Cleared: {final_state['final_safe_response']}")
print("="*50)

# 4. Generate the Audio Interface
print("\n🔊 AI Audio Output:")
display(Audio(final_stadte['output_audio_path'], autoplay=True))

from faster_whisper import WhisperModel

print("Re-awakening the Ear and loading it back into VRAM...")

# Re-initialize the specific multilingual model
model_size = "large-v3-turbo"

# Force it back onto the GPU with half-precision memory
audio_model = WhisperModel(model_size, device="cuda", compute_type="float16")

print("✅ The Ear is back online and resting in memory!")

import requests
import json
from typing import TypedDict, Optional

# ==========================================
# 1. The Upgraded Agentic State
# ==========================================
class AgenticState(TypedDict):
    user_audio_path: str
    detected_language: str
    user_transcript: str
    api_routing_flag: str         # Tracks which external system was accessed
    retrieved_context: str        # The fused, cleaned data from the APIs
    draft_response: str
    final_safe_response: str
    output_audio_path: str
    error_flag: Optional[str]

# ==========================================
# 2. The Dynamic API & Data Fusion Node
# ==========================================
def dynamic_api_node(state):
    query = state["user_transcript"].lower()
    fused_context = ""
    route_taken = "none"

    try:
        # Route 1: Real-Time Weather API (Open-Meteo, Keyless)
        if "weather" in query or "temperature" in query or "mausam" in query: # 'mausam' handles Hindi edge cases
            route_taken = "open_meteo_api"
            # Hardcoded coordinates for the prototype (e.g., Hubballi/Delhi area logic),
            # In V2, this would be a dynamic location extractor.
            url = "https://api.open-meteo.com/v1/forecast?latitude=28.61&longitude=77.20&current_weather=true"
            response = requests.get(url, timeout=5)

            if response.status_code == 200:
                data = response.json()["current_weather"]
                # Data Fusion: Stripping JSON formatting into a dense semantic string
                fused_context = f"Live Weather Data: Temperature is {data['temperature']}°C, Windspeed {data['windspeed']} km/h."
            else:
                fused_context = "API Error: Weather server rejected the request."

        # Route 2: Real-Time Knowledge API (Wikipedia REST API, Keyless)
        else:
            route_taken = "wikipedia_api"
            # Extract the core noun (Naive extraction for prototype)
            # We take the last word of the transcript assuming it's the subject (e.g., "Tell me about quantum")
            search_term = query.split()[-1]
            url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{search_term}"
            response = requests.get(url, timeout=5)

            if response.status_code == 200:
                data = response.json()
                # Data Fusion: Extracting only the abstract to preserve VRAM context limits
                fused_context = f"Live Encyclopedia Data: {data.get('extract', 'No abstract available.')}"
            else:
                fused_context = "API Error: No live encyclopedia entry found for that subject."

    # Edge Case Handling: Total Network Failure
    except requests.exceptions.RequestException as e:
        fused_context = f"CRITICAL EDGE CASE: External API Timeout or Network Failure. Details: {str(e)}"
        route_taken = "api_failure"

    # Mutate the state with the fused external data
    state["api_routing_flag"] = route_taken
    state["retrieved_context"] = fused_context

    return state

# ==========================================
# 3. The Edge-Case Resilient Brain Node
# ==========================================
def advanced_brain_node(state):
    user_text = state["user_transcript"]
    lang = state["detected_language"]
    context = state["retrieved_context"]
    route = state["api_routing_flag"]

    # Advanced System Prompting for Real-Time Volatility
    system_prompt = f"""You are a highly analytical AI reasoning engine.
    The user spoke in language code: '{lang}'.

    REAL-TIME DATA FEED: {context}
    DATA SOURCE ROUTE: {route}

    OPERATING CONSTRAINTS:
    1. If the Real-Time Data contains an 'API Error' or 'CRITICAL EDGE CASE', you must inform the user that the external sensors are offline, but attempt to answer using your internal knowledge if safe to do so.
    2. Do not blindly read the data. Synthesize it naturally into a conversational response.
    3. CRITICAL: Your final output MUST be written in the exact same language as the user's language code ({lang}).
    """

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_text}
    ]

    # Execute matrix generation
    outputs = reasoning_pipeline(messages)
    generated_text = outputs[0]["generated_text"][-1]["content"]

    state["draft_response"] = generated_text

    return state

from langgraph.graph import StateGraph, START, END

# ==========================================
# 4. The Agentic API Orchestrator (V5)
# ==========================================
workflow = StateGraph(AgenticState)

# Mount the newly engineered nodes alongside the existing infrastructure
workflow.add_node("ear", ear_node)
workflow.add_node("dynamic_api", dynamic_api_node)     # <- NEW LIVE DATA NODE
workflow.add_node("advanced_brain", advanced_brain_node) # <- NEW REASONING NODE
workflow.add_node("guardrail", guardrail_node)
workflow.add_node("voicebox", voicebox_node)

# Wire the dynamic assembly line
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "dynamic_api")                # Ear routes directly to the API fetcher
workflow.add_edge("dynamic_api", "advanced_brain")     # Fused JSON goes to the LLM Brain
workflow.add_edge("advanced_brain", "guardrail")
workflow.add_edge("guardrail", "voicebox")
workflow.add_edge("voicebox", END)

# Compile the Master Graph
dynamic_ai_pipeline = workflow.compile()

import requests
import soundfile as sf
from typing import TypedDict, Optional
from langgraph.graph import StateGraph, START, END

# ==========================================
# 0. The Blueprint (State)
# ==========================================
class AgenticState(TypedDict):
    user_audio_path: str
    detected_language: str
    user_transcript: str
    api_routing_flag: str
    retrieved_context: str
    draft_response: str
    final_safe_response: str
    output_audio_path: str
    error_flag: Optional[str]

# ==========================================
# 1. Node 1: The Ear (With Hindi/Urdu Patch)
# ==========================================
def ear_node(state):
    audio_path = state["user_audio_path"]
    segments, info = audio_model.transcribe(audio_path, beam_size=5)
    full_transcript = " ".join([segment.text for segment in segments])

    detected_lang = info.language
    if detected_lang == "ur":  # Hindustani edge-case patch
        detected_lang = "hi"

    state["detected_language"] = detected_lang
    state["user_transcript"] = full_transcript
    return state

# ==========================================
# 2. Node 2: The Real-Time API Data Fusion
# ==========================================
def dynamic_api_node(state):
    query = state["user_transcript"].lower()
    fused_context = ""
    route_taken = "none"

    try:
        if "weather" in query or "temperature" in query or "mausam" in query:
            route_taken = "open_meteo_api"
            url = "https://api.open-meteo.com/v1/forecast?latitude=28.61&longitude=77.20&current_weather=true"
            response = requests.get(url, timeout=5)
            if response.status_code == 200:
                data = response.json()["current_weather"]
                fused_context = f"Live Weather: Temp {data['temperature']}°C, Wind {data['windspeed']} km/h."
            else:
                fused_context = "API Error: Weather server rejected the request."
        else:
            route_taken = "wikipedia_api"
            search_term = query.split()[-1]
            url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{search_term}"
            response = requests.get(url, timeout=5)
            if response.status_code == 200:
                data = response.json()
                fused_context = f"Live Encyclopedia Data: {data.get('extract', 'No abstract available.')}"
            else:
                fused_context = "API Error: No live encyclopedia entry found."
    except requests.exceptions.RequestException as e:
        fused_context = f"CRITICAL EDGE CASE: Network Failure. Details: {str(e)}"
        route_taken = "api_failure"

    state["api_routing_flag"] = route_taken
    state["retrieved_context"] = fused_context
    return state

# ==========================================
# 3. Node 3: The Edge-Case Resilient Brain
# ==========================================
def advanced_brain_node(state):
    user_text = state["user_transcript"]
    lang = state["detected_language"]
    context = state["retrieved_context"]
    route = state["api_routing_flag"]

    system_prompt = f"""You are a highly analytical AI reasoning engine.
    User language code: '{lang}'.
    REAL-TIME DATA FEED: {context}
    DATA SOURCE ROUTE: {route}

    CRITICAL: Answer using the Real-Time Data. Your final output MUST be in the exact language code ({lang})."""

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_text}]
    outputs = reasoning_pipeline(messages)
    state["draft_response"] = outputs[0]["generated_text"][-1]["content"]
    return state

# ==========================================
# 4. Node 4: The Guardrail (Policy Filter)
# ==========================================
def guardrail_node(state):
    drafted_text = state["draft_response"]
    policy_labels = ["safe and helpful", "toxic, hateful, or harmful advice"]
    classification = policy_classifier(drafted_text, policy_labels)

    if classification['labels'][0] == "toxic, hateful, or harmful advice":
        state["final_safe_response"] = "Policy Override: I cannot fulfill this request safely."
        state["error_flag"] = "Safety Violation Triggered"
    else:
        state["final_safe_response"] = drafted_text
    return state

# ==========================================
# 5. Node 5: The Voicebox (Acoustic Synth)
# ==========================================
def voicebox_node(state):
    text_to_speak = state["final_safe_response"]
    voice_description = "A clear, professional female voice speaking at a moderate pace."

    input_ids = tts_tokenizer(voice_description, return_tensors="pt").input_ids.to("cuda")
    prompt_input_ids = tts_tokenizer(text_to_speak, return_tensors="pt").input_ids.to("cuda")

    generation = tts_model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
    audio_waveform = generation.cpu().numpy().squeeze()

    output_filename = "ai_final_response.wav"
    sf.write(output_filename, audio_waveform, tts_model.config.sampling_rate)
    state["output_audio_path"] = output_filename
    return state

# ==========================================
# 6. Assemble the Agentic Graph
# ==========================================
workflow = StateGraph(AgenticState)

workflow.add_node("ear", ear_node)
workflow.add_node("dynamic_api", dynamic_api_node)
workflow.add_node("advanced_brain", advanced_brain_node)
workflow.add_node("guardrail", guardrail_node)
workflow.add_node("voicebox", voicebox_node)

workflow.add_edge(START, "ear")
workflow.add_edge("ear", "dynamic_api")
workflow.add_edge("dynamic_api", "advanced_brain")
workflow.add_edge("advanced_brain", "guardrail")
workflow.add_edge("guardrail", "voicebox")
workflow.add_edge("voicebox", END)

dynamic_ai_pipeline = workflow.compile()
print("✅ Master Logic Block loaded and Agentic Graph compiled!")

import json
import re

# ==========================================
# 1. The AgriTech State Blueprint
# ==========================================
class AgenticState(TypedDict):
    user_audio_path: str
    detected_language: str
    user_transcript: str
    extracted_params: dict        # NEW: Holds the JSON variables for the APIs
    api_routing_flag: str
    retrieved_context: str
    draft_response: str
    final_safe_response: str
    output_audio_path: str
    error_flag: Optional[str]

# ==========================================
# 2. Node 2A: The Semantic Extractor
# ==========================================
# This acts as the "Pre-Brain". It does not give advice; it only extracts data.
def parameter_extraction_node(state):
    query = state["user_transcript"]

    # We force the LLM to output ONLY a JSON dictionary
    extraction_prompt = f"""Extract the farming location and the specific crop mentioned in this text.
    If location is missing, default to "Hubballi". If crop is missing, default to "General".
    Output ONLY a valid JSON object in this exact format: {{"location": "City Name", "crop": "Crop Name"}}

    User Text: {query}"""

    messages = [{"role": "system", "content": extraction_prompt}]

    # We cap the tokens at 50 so this pass executes in just 1-2 seconds
    outputs = reasoning_pipeline(messages, max_new_tokens=50)
    raw_output = outputs[0]["generated_text"][-1]["content"]

    # Heuristic parsing to clean the LLM's output and extract the pure dictionary
    try:
        # Finds everything between { and }
        json_str = re.search(r'\{.*\}', raw_output, re.DOTALL).group()
        extracted_data = json.loads(json_str)
    except:
        # Fallback if the LLM hallucinates formatting
        extracted_data = {"location": "Hubballi", "crop": "General"}

    state["extracted_params"] = extracted_data
    return state

import requests

# ==========================================
# 3. Node 2B: The Real-Time Agri Data Fetcher
# ==========================================
def agritech_api_node(state):
    params = state["extracted_params"]
    location = params.get("location", "Hubballi")
    crop = params.get("crop", "General")

    fused_context = f"--- REAL-TIME DATA FOR {location.upper()} | CROP: {crop.upper()} ---\n"

    # ---------------------------------------------------------
    # CALL 1: WEATHER (Live via Open-Meteo)
    # ---------------------------------------------------------
    try:
        # For prototype, we use fixed coords, but normally you'd geocode the 'location' variable
        weather_url = "https://api.open-meteo.com/v1/forecast?latitude=15.36&longitude=75.12&current_weather=true"
        w_res = requests.get(weather_url, timeout=5)
        if w_res.status_code == 200:
            w_data = w_res.json()["current_weather"]
            fused_context += f"[WEATHER]: Temp {w_data['temperature']}°C, Wind {w_data['windspeed']}km/h. "
    except:
         fused_context += "[WEATHER]: Sensors offline. "

    # ---------------------------------------------------------
    # CALL 2: MARKET PRICES (Simulating data.gov.in Mandi API)
    # ---------------------------------------------------------
    # In production: requests.get(f"https://api.data.gov.in/resource/...?api-key=YOUR_KEY&filters[commodity]={crop}")
    if crop.lower() != "general":
        # Simulating a successful JSON response from the government server
        mock_mandi_data = {"modal_price": "2,450 INR/Quintal", "trend": "Rising 2% since last week"}
        fused_context += f"\n[MARKET]: {crop} is trading at {mock_mandi_data['modal_price']} ({mock_mandi_data['trend']}). "
    else:
        fused_context += "\n[MARKET]: No specific crop detected to fetch prices. "

    # ---------------------------------------------------------
    # CALL 3: SOIL HEALTH (Simulating National SHC Database)
    # ---------------------------------------------------------
    # Simulating regional soil profile retrieval
    mock_soil_data = {"type": "Black Cotton Soil", "nitrogen": "Low", "phosphorus": "Medium", "ph": "7.5"}
    fused_context += f"\n[SOIL PROFILE]: {mock_soil_data['type']}, N:{mock_soil_data['nitrogen']}, P:{mock_soil_data['phosphorus']}, pH:{mock_soil_data['ph']}."

    state["retrieved_context"] = fused_context
    state["api_routing_flag"] = "Agri_Fusion_API"

    return state

# ==========================================
# Node 3: The Agronomist Brain
# ==========================================
def advanced_agronomist_node(state):
    user_text = state["user_transcript"]
    lang = state["detected_language"]
    context = state["retrieved_context"]
    params = state.get("extracted_params", {})
    crop = params.get("crop", "General")

    # The Domain-Specific System Prompt
    system_prompt = f"""You are a highly analytical expert Indian Agronomist.
    User language code: '{lang}'.
    Target Crop: {crop.upper()}

    REAL-TIME FUSED DATA:
    {context}

    OPERATING CONSTRAINTS:
    1. Analyze the soil profile, weather, and market trends provided in the data.
    2. Give practical, high-yield, and cost-effective farming advice based strictly on this data.
    3. Do not read the raw data back to the user; synthesize it into actionable steps.
    4. CRITICAL: Your final output MUST be written in the exact same language as the user's language code ({lang})."""

    # Execute the reasoning matrix
    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_text}]
    outputs = reasoning_pipeline(messages)

    state["draft_response"] = outputs[0]["generated_text"][-1]["content"]
    return state

# ==========================================
# Node 4: The Agricultural Policy Filter
# ==========================================
def agricultural_guardrail_node(state):
    drafted_text = state["draft_response"]

    # Custom Zero-Shot Policy Labels for Indian Agriculture
    policy_labels = [
        "safe and compliant Indian agricultural advice",
        "promotes banned pesticides, stubble burning, or hazardous chemical mixing"
    ]

    # Execute the probability matrix scan
    classification = policy_classifier(drafted_text, policy_labels)
    top_label = classification['labels'][0]

    # The Routing Logic
    if top_label == "promotes banned pesticides, stubble burning, or hazardous chemical mixing":
        # Hard override if the LLM hallucinates dangerous advice
        state["final_safe_response"] = "Policy Override: The generated advice violates Indian agricultural safety norms. Please consult a local Krishi Vigyan Kendra."
        state["error_flag"] = "Agricultural Safety Violation"
    else:
        # Promote the safe text to the Voicebox
        state["final_safe_response"] = drafted_text

    return state

import requests
import json
import re
import soundfile as sf
from typing import TypedDict, Optional
from langgraph.graph import StateGraph, START, END

# ==========================================
# 0. The AgriTech State Blueprint
# ==========================================
class AgenticState(TypedDict):
    user_audio_path: str
    detected_language: str
    user_transcript: str
    extracted_params: dict        # Stores the parsed JSON for API routing
    api_routing_flag: str
    retrieved_context: str        # The fused weather/soil/market data
    draft_response: str
    final_safe_response: str
    output_audio_path: str
    error_flag: Optional[str]

# ==========================================
# 1. Node 1: The Polyglot Ear
# ==========================================
def ear_node(state):
    audio_path = state["user_audio_path"]
    segments, info = audio_model.transcribe(audio_path, beam_size=5)
    full_transcript = " ".join([segment.text for segment in segments])

    # Hindustani/Urdu acoustic overlap patch
    detected_lang = info.language
    if detected_lang == "ur":
        detected_lang = "hi"

    state["detected_language"] = detected_lang
    state["user_transcript"] = full_transcript
    return state

# ==========================================
# 2. Node 2A: Semantic Parameter Extraction
# ==========================================
def parameter_extraction_node(state):
    query = state["user_transcript"]

    # Constraining the LLM to act as a pure JSON parser
    extraction_prompt = f"""Extract the farming location and the specific crop mentioned in this text.
    If location is missing, default to "Hubballi". If crop is missing, default to "General".
    Output ONLY a valid JSON object: {{"location": "City Name", "crop": "Crop Name"}}

    User Text: {query}"""

    messages = [{"role": "system", "content": extraction_prompt}]
    outputs = reasoning_pipeline(messages, max_new_tokens=50)
    raw_output = outputs[0]["generated_text"][-1]["content"]

    # Heuristic regex to isolate the JSON dictionary
    try:
        json_str = re.search(r'\{.*\}', raw_output, re.DOTALL).group()
        extracted_data = json.loads(json_str)
    except:
        extracted_data = {"location": "Hubballi", "crop": "General"}

    state["extracted_params"] = extracted_data
    return state

# ==========================================
# 3. Node 2B: Real-Time Data Fusion (APIs)
# ==========================================
def agritech_api_node(state):
    params = state["extracted_params"]
    location = params.get("location", "Hubballi")
    crop = params.get("crop", "General")

    fused_context = f"--- REAL-TIME DATA FOR {location.upper()} | CROP: {crop.upper()} ---\n"

    # Live Weather Data (Open-Meteo)
    try:
        weather_url = "https://api.open-meteo.com/v1/forecast?latitude=15.36&longitude=75.12&current_weather=true"
        w_res = requests.get(weather_url, timeout=5)
        if w_res.status_code == 200:
            w_data = w_res.json()["current_weather"]
            fused_context += f"[WEATHER]: Temp {w_data['temperature']}°C, Wind {w_data['windspeed']}km/h. "
    except:
         fused_context += "[WEATHER]: Sensors offline. "

    # Simulated Mandi Market Data
    if crop.lower() != "general":
        fused_context += f"\n[MARKET]: {crop} is trading at 2,450 INR/Quintal (Rising 2%). "
    else:
        fused_context += "\n[MARKET]: No specific crop detected. "

    # Simulated Soil Health Card Data
    fused_context += "\n[SOIL PROFILE]: Black Cotton Soil, N:Low, P:Medium, pH:7.5."

    state["retrieved_context"] = fused_context
    state["api_routing_flag"] = "Agri_Fusion_API"
    return state

# ==========================================
# 4. Node 3: The Agronomist Brain
# ==========================================
def advanced_agronomist_node(state):
    user_text = state["user_transcript"]
    lang = state["detected_language"]
    context = state["retrieved_context"]
    crop = state["extracted_params"].get("crop", "General")

    # Persona Injection & Constraint Matrix
    system_prompt = f"""You are a highly analytical expert Indian Agronomist.
    User language code: '{lang}'. Target Crop: {crop.upper()}
    REAL-TIME FUSED DATA: {context}

    CRITICAL CONSTRAINTS:
    1. Give practical, high-yield advice based strictly on the fused data.
    2. Your final output MUST be written in the exact same language as the user's language code ({lang})."""

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_text}]
    outputs = reasoning_pipeline(messages)
    state["draft_response"] = outputs[0]["generated_text"][-1]["content"]
    return state

# ==========================================
# 5. Node 4: The Agricultural Policy Guardrail
# ==========================================
def agricultural_guardrail_node(state):
    drafted_text = state["draft_response"]
    policy_labels = [
        "safe and compliant Indian agricultural advice",
        "promotes banned pesticides, stubble burning, or hazardous chemical mixing"
    ]

    classification = policy_classifier(drafted_text, policy_labels)
    if classification['labels'][0] == "promotes banned pesticides, stubble burning, or hazardous chemical mixing":
        state["final_safe_response"] = "Policy Override: The generated advice violates Indian agricultural safety norms."
        state["error_flag"] = "Agricultural Safety Violation"
    else:
        state["final_safe_response"] = drafted_text
    return state

# ==========================================
# 6. Node 5: The Polyglot Voicebox
# ==========================================
def voicebox_node(state):
    text_to_speak = state["final_safe_response"]
    voice_description = "A clear, professional female voice speaking at a moderate pace."

    input_ids = tts_tokenizer(voice_description, return_tensors="pt").input_ids.to("cuda")
    prompt_input_ids = tts_tokenizer(text_to_speak, return_tensors="pt").input_ids.to("cuda")

    generation = tts_model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
    sf.write("agri_final_response.wav", generation.cpu().numpy().squeeze(), tts_model.config.sampling_rate)

    state["output_audio_path"] = "agri_final_response.wav"
    return state

# ==========================================
# 7. Assemble the Agentic Graph
# ==========================================
workflow = StateGraph(AgenticState)

# Mount the 6 discrete computing nodes
workflow.add_node("ear", ear_node)
workflow.add_node("extractor", parameter_extraction_node)
workflow.add_node("api_fusion", agritech_api_node)
workflow.add_node("agronomist", advanced_agronomist_node)
workflow.add_node("guardrail", agricultural_guardrail_node)
workflow.add_node("voicebox", voicebox_node)

# Wire the complex topological flow
workflow.add_edge(START, "ear")
workflow.add_edge("ear", "extractor")
workflow.add_edge("extractor", "api_fusion")
workflow.add_edge("api_fusion", "agronomist")
workflow.add_edge("agronomist", "guardrail")
workflow.add_edge("guardrail", "voicebox")
workflow.add_edge("voicebox", END)

# Compile the Master Graph into executable VRAM memory
agritech_pipeline = workflow.compile()
print("✅ Master AgriTech Logic Block loaded and Agentic Graph compiled!")

from IPython.display import Audio, display

# 1. Initialize the Blank Clipboard
initial_state = {
    "user_audio_path": "/content/sample_audio_3.mp3", # <--- PASTE EXACT PATH HERE
    # ... (rest of the dictionary stays the same),
    "detected_language": "",
    "user_transcript": "",
    "extracted_params": {},
    "api_routing_flag": "",
    "retrieved_context": "",
    "draft_response": "",
    "final_safe_response": "",
    "output_audio_path": "",
    "error_flag": None
}

print("🚜 INITIATING AGRITECH PIPELINE...")
print("Executing: Ear -> Extractor -> Data Fusion -> Agronomist -> Guardrail -> Voicebox")

# 2. Trigger the Automated Assembly Line
final_state = agritech_pipeline.invoke(initial_state)

# 3. Display the Granular Systemic Outputs
print("\n" + "="*60)
print(f"🎙️ Transcript:       {final_state['user_transcript']}")
print(f"🧠 Extracted JSON:   {final_state['extracted_params']}")
print(f"📡 Fused API Data:\n{final_state['retrieved_context']}")
print(f"\n🛡️ Policy Output:    {final_state['final_safe_response']}")
print("="*60)

# 4. Generate the Audio Interface
print("\n🔊 Agronomist Voice Output:")
display(Audio(final_state['output_audio_path'], autoplay=True))

!pip install -q gTTS

!pip install -q gTTS>=8.2.1

import warnings
from gtts import gTTS
from langgraph.graph import StateGraph, START, END

# 1. Suppress the harmless audio and system warnings
warnings.filterwarnings("ignore")

# ==========================================
# Upgraded Node 3: The Agronomist Brain
# ==========================================
def advanced_agronomist_node(state):
    user_text = state["user_transcript"]
    lang = state["detected_language"]
    context = state["retrieved_context"]
    crop = state.get("extracted_params", {}).get("crop", "General")

    system_prompt = f"""You are a highly analytical expert Indian Agronomist.
    User language code: '{lang}'. Target Crop: {crop.upper()}
    REAL-TIME FUSED DATA: {context}

    CRITICAL CONSTRAINTS:
    1. Give practical, high-yield advice based strictly on the fused data.
    2. Your final output MUST be written in the exact same language as the user's language code ({lang})."""

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_text}]

    # PATCH: Increased max_new_tokens to 512 to prevent cut-offs
    # PATCH: Added pad_token_id to silence the HuggingFace warning
    outputs = reasoning_pipeline(
        messages,
        max_new_tokens=512,
        pad_token_id=llm_tokenizer.eos_token_id
    )

    state["draft_response"] = outputs[0]["generated_text"][-1]["content"]
    return state

# ==========================================
# Upgraded Node 5: The Polyglot Voicebox
# ==========================================
def voicebox_node(state):
    text_to_speak = state["final_safe_response"]
    lang_code = state["detected_language"] # This will naturally route to 'hi' for Hindi

    # PATCH: Using gTTS for flawless native Indian language recitation
    try:
        tts = gTTS(text=text_to_speak, lang=lang_code, slow=False)
        output_filename = "agri_final_response.mp3"
        tts.save(output_filename)
        state["output_audio_path"] = output_filename
    except Exception as e:
        state["error_flag"] = f"Voice Engine Error: {str(e)}"

    return state

# ==========================================
# Re-Assemble the Agentic Graph
# ==========================================
workflow = StateGraph(AgenticState)

# We use the existing Nodes 1, 2A, 2B, and 4 from your memory, plus the two new ones
workflow.add_node("ear", ear_node)
workflow.add_node("extractor", parameter_extraction_node)
workflow.add_node("api_fusion", agritech_api_node)
workflow.add_node("agronomist", advanced_agronomist_node) # UPGRADED
workflow.add_node("guardrail", agricultural_guardrail_node)
workflow.add_node("voicebox", voicebox_node)              # UPGRADED

workflow.add_edge(START, "ear")
workflow.add_edge("ear", "extractor")
workflow.add_edge("extractor", "api_fusion")
workflow.add_edge("api_fusion", "agronomist")
workflow.add_edge("agronomist", "guardrail")
workflow.add_edge("guardrail", "voicebox")
workflow.add_edge("voicebox", END)

agritech_pipeline = workflow.compile()
print("✅ Node optimizations complete. Pipeline re-compiled!")

# ==========================================
# Upgraded Node 2A: Semantic Extractor (With Translation)
# ==========================================
def parameter_extraction_node(state):
    query = state["user_transcript"]

    # PATCH: We force the LLM to translate the crop to English for the API
    extraction_prompt = f"""Extract the farming location and the specific crop mentioned in this text.
    CRITICAL: Translate the crop name into standard English (e.g., if user says 'रूई', output 'Cotton').
    If location is missing, default to "Hubballi". If crop is missing, default to "General".
    Output ONLY a valid JSON object: {{"location": "City Name", "crop": "Crop Name"}}

    User Text: {query}"""

    messages = [{"role": "system", "content": extraction_prompt}]
    outputs = reasoning_pipeline(messages, max_new_tokens=64)
    raw_output = outputs[0]["generated_text"][-1]["content"]

    try:
        json_str = re.search(r'\{.*\}', raw_output, re.DOTALL).group()
        extracted_data = json.loads(json_str)
    except:
        extracted_data = {"location": "Hubballi", "crop": "General"}

    state["extracted_params"] = extracted_data
    return state

# ==========================================
# Upgraded Node 3: The Agronomist Brain (With Length Control)
# ==========================================
def advanced_agronomist_node(state):
    user_text = state["user_transcript"]
    lang = state["detected_language"]
    context = state["retrieved_context"]
    crop = state.get("extracted_params", {}).get("crop", "General")

    # PATCH: Strict length and structure constraints added to the prompt
    system_prompt = f"""You are an expert Indian Agronomist.
    User language code: '{lang}'. Target Crop: {crop.upper()}
    REAL-TIME FUSED DATA: {context}

    CRITICAL CONSTRAINTS:
    1. Give practical advice based strictly on the fused data.
    2. BE CONCISE. Provide EXACTLY 3 short, actionable bullet points. Do not write a long conclusion.
    3. Your output MUST be in the exact same language as the user's language code ({lang})."""

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_text}]

    # PATCH: Increased token limit to 1024 to handle Hindi tokenization bloat
    outputs = reasoning_pipeline(
        messages,
        max_new_tokens=1024,
        pad_token_id=llm_tokenizer.eos_token_id
    )

    state["draft_response"] = outputs[0]["generated_text"][-1]["content"]
    return state

# ==========================================
# Re-Assemble the Graph
# ==========================================
workflow = StateGraph(AgenticState)

workflow.add_node("ear", ear_node)
workflow.add_node("extractor", parameter_extraction_node) # UPGRADED
workflow.add_node("api_fusion", agritech_api_node)
workflow.add_node("agronomist", advanced_agronomist_node) # UPGRADED
workflow.add_node("guardrail", agricultural_guardrail_node)
workflow.add_node("voicebox", voicebox_node)

workflow.add_edge(START, "ear")
workflow.add_edge("ear", "extractor")
workflow.add_edge("extractor", "api_fusion")
workflow.add_edge("api_fusion", "agronomist")
workflow.add_edge("agronomist", "guardrail")
workflow.add_edge("guardrail", "voicebox")
workflow.add_edge("voicebox", END)

agritech_pipeline = workflow.compile()
print("✅ Token limits increased and Extractor translated. Pipeline re-compiled!")

# ==========================================
# Upgraded Node 3: The Deep-Reasoning Agronomist
# ==========================================
def advanced_agronomist_node(state):
    user_text = state["user_transcript"]
    lang = state["detected_language"]
    context = state["retrieved_context"]
    crop = state.get("extracted_params", {}).get("crop", "General")

    # PATCH: Deep Analytical Cognitive Framework
    system_prompt = f"""You are an elite, highly analytical Indian Agronomist.
    User language code: '{lang}'. Target Crop: {crop.upper()}

    REAL-TIME FUSED DATA:
    {context}

    CRITICAL REASONING FRAMEWORK:
    You must process the fused data deeply and explain how the variables connect to each other. Structure your guidance to be incredibly easy for a farmer to follow, yet analytically rigorous.

    Format your response exactly like this:
    1. स्थिति का विश्लेषण (Situation Analysis): Briefly explain how the current weather, soil, and market data impact this specific crop.
    2. तुरंत करने योग्य कार्य (Immediate Actions): Step-by-step guidance for the next 48 hours (e.g., watering, sowing).
    3. दीर्घकालिक देखभाल (Preventive Care): Granular advice on fertilizers or pest control based on the soil profile.

    CONSTRAINTS:
    - Cater to any edge case logically and safely.
    - Be highly empathetic, clear, and detailed.
    - Your final output MUST be in the exact language code ({lang})."""

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_text}]

    # PATCH: Massive token buffer for deep processing; Temperature at 0.4 for calculated adaptability
    outputs = reasoning_pipeline(
        messages,
        max_new_tokens=2048,
        temperature=0.4,
        pad_token_id=llm_tokenizer.eos_token_id
    )

    state["draft_response"] = outputs[0]["generated_text"][-1]["content"]
    return state

# ==========================================
# Re-Assemble the Graph with the Ultimate Brain
# ==========================================
workflow = StateGraph(AgenticState)

workflow.add_node("ear", ear_node)
workflow.add_node("extractor", parameter_extraction_node)
workflow.add_node("api_fusion", agritech_api_node)
workflow.add_node("agronomist", advanced_agronomist_node) # DEEP REASONING UPGRADE
workflow.add_node("guardrail", agricultural_guardrail_node)
workflow.add_node("voicebox", voicebox_node)

workflow.add_edge(START, "ear")
workflow.add_edge("ear", "extractor")
workflow.add_edge("extractor", "api_fusion")
workflow.add_edge("api_fusion", "agronomist")
workflow.add_edge("agronomist", "guardrail")
workflow.add_edge("guardrail", "voicebox")
workflow.add_edge("voicebox", END)

agritech_pipeline = workflow.compile()
print("✅ Deep Reasoning Framework injected. Pipeline re-compiled!")